{
	"version": 1502915783,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/woodtable-sheet0.png",
		"images/scrollablefieldoftext-sheet0.png",
		"images/mask-sheet0.png",
		"images/frame.png",
		"images/scroll_position-sheet0.png",
		"images/diarytext.png",
		"images/tiledbackground.png",
		"media/57675__sound-master__effect-2.m4a",
		"media/57675__sound-master__effect-2.ogg",
		"media/untitled.m4a",
		"media/untitled.ogg",
		"media/fireplace2.ogg",
		"media/rain_001.ogg",
		"media/space ambient3.m4a",
		"media/space ambient3.ogg",
		"media/space ambient8.m4a",
		"media/space ambient8.ogg",
		"media/alarm.m4a",
		"media/alarm.ogg",
		"media/alarm2.m4a",
		"media/alarm2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"loading-logo.png",
		"icon-256.png"
	]
}