{
	"version": 1504190643,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/floorgrass.png",
		"images/hpmpstamina.png",
		"images/level.png",
		"images/pasekhp-sheet0.png",
		"images/pasekmp-sheet0.png",
		"images/pasekst-sheet0.png",
		"images/plus-sheet0.png",
		"images/plus-sheet1.png",
		"images/1player-sheet0.png",
		"images/1player-sheet1.png",
		"images/zasięggracza-sheet0.png",
		"images/trees-sheet0.png",
		"images/trees-sheet1.png",
		"images/bushes-sheet0.png",
		"images/1enemy-sheet0.png",
		"images/1enemy-sheet1.png",
		"images/1enemy-sheet2.png",
		"images/zasiegsnake-sheet0.png",
		"images/hit-sheet0.png",
		"images/hit-sheet1.png",
		"images/enemyhpbar-sheet0.png",
		"images/cel-sheet0.png",
		"images/wall-sheet0.png",
		"images/fireball-sheet0.png",
		"images/wybuch-sheet0.png",
		"images/chest-sheet0.png",
		"images/chest-sheet1.png",
		"images/drzwi-sheet0.png",
		"images/drzwi-sheet1.png",
		"images/trapfield-sheet0.png",
		"images/llicznikobrazenplayer.png",
		"images/llicznikobrazenwrog.png",
		"images/llicznikxp.png",
		"images/floorsand.png",
		"images/tiledbackground3.png",
		"images/gallery_569_9_-sheet0.png",
		"images/magia-sheet0.png",
		"images/graj-sheet0.png",
		"images/sprite-sheet0.png",
		"images/imie-sheet0.png",
		"images/przydomek-sheet0.png",
		"images/particles.png",
		"images/tiledbackground4.png",
		"images/npc-sheet0.png",
		"images/npc-sheet1.png",
		"images/zrzutekranu-sheet0.png",
		"images/zrzutekranu2-sheet0.png",
		"images/lens-sheet0.png",
		"images/deadplayer-sheet0.png",
		"images/cow-sheet0.png",
		"images/cow-sheet1.png",
		"images/clock-sheet0.png",
		"images/clock-sheet1.png",
		"images/night-sheet0.png",
		"images/blysk-sheet0.png",
		"images/fence-sheet0.png",
		"images/anvil-sheet0.png",
		"images/lensfx-sheet0.png",
		"images/rabbit-sheet0.png",
		"images/nora-sheet0.png",
		"images/slotbackpack-sheet0.png",
		"images/slotbackpack-sheet1.png",
		"images/miejscebroń-sheet0.png",
		"images/miejscetarcza-sheet0.png",
		"images/miejscezbroja-sheet0.png",
		"images/miejscehelm-sheet0.png",
		"images/miejscebuty-sheet0.png",
		"images/1itemsg-sheet0.png",
		"images/miejsceamulet-sheet0.png",
		"images/floorwood.png",
		"images/info-sheet0.png",
		"images/button2-sheet0.png",
		"images/button2-sheet1.png",
		"images/button-sheet0.png",
		"images/button-sheet1.png",
		"images/button-sheet2.png",
		"images/use-sheet0.png",
		"images/loadinglogo-sheet0.png",
		"images/icoico-sheet0.png",
		"images/guiatributes-sheet0.png",
		"images/guiatributes-sheet1.png",
		"images/guiskills-sheet0.png",
		"images/guiskills-sheet1.png",
		"images/guiskills-sheet2.png",
		"images/guitable-sheet0.png",
		"images/guitable-sheet1.png",
		"images/furniture-sheet0.png",
		"images/r-sheet0.png",
		"images/r-sheet1.png",
		"images/tutorial-sheet0.png",
		"images/guispellbook-sheet0.png",
		"images/guispellbook-sheet1.png",
		"images/guispellbook-sheet2.png",
		"images/guisneak-sheet0.png",
		"images/guisneak-sheet1.png",
		"images/guisneak-sheet2.png",
		"images/dialogeventtrigger-sheet0.png",
		"images/dialog.png",
		"images/light-sheet0.png",
		"images/light-sheet1.png",
		"images/guispellbook2-sheet0.png",
		"images/guispellbook2-sheet1.png",
		"images/guispellbook2-sheet2.png",
		"images/slotbackpack2-sheet0.png",
		"images/shoptable-sheet0.png",
		"images/1itemsshop-sheet0.png",
		"images/paypalbuynowbutton-sheet0.png",
		"images/tiledbackground.png",
		"media/level up.m4a",
		"media/level up.ogg",
		"media/click.m4a",
		"media/click.ogg",
		"media/step1.m4a",
		"media/step1.ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/hit_hurt3.m4a",
		"media/hit_hurt3.ogg",
		"media/fireball0_001.m4a",
		"media/fireball0_001.ogg",
		"media/fireball_001.m4a",
		"media/fireball_001.ogg",
		"media/chest_open_001.m4a",
		"media/chest_open_001.ogg",
		"media/lock 1_001.m4a",
		"media/lock 1_001.ogg",
		"media/woodhit.m4a",
		"media/woodhit.ogg",
		"media/trap click_001.m4a",
		"media/trap click_001.ogg",
		"media/wood_crate_break3_001.m4a",
		"media/wood_crate_break3_001.ogg",
		"media/spike trap.m4a",
		"media/spike trap.ogg",
		"media/disarm trap.m4a",
		"media/disarm trap.ogg",
		"media/drink potion.m4a",
		"media/drink potion.ogg",
		"media/scream dead.m4a",
		"media/scream dead.ogg",
		"media/blinkstone.m4a",
		"media/blinkstone.ogg",
		"media/krowa.m4a",
		"media/krowa.ogg",
		"media/krowa2.m4a",
		"media/krowa2.ogg",
		"media/krowa3.m4a",
		"media/krowa3.ogg",
		"media/krowa4.m4a",
		"media/krowa4.ogg",
		"media/bunny.m4a",
		"media/bunny.ogg",
		"media/critical.m4a",
		"media/critical.ogg",
		"media/grab.m4a",
		"media/grab.ogg",
		"media/swordeguip.m4a",
		"media/swordeguip.ogg",
		"media/shield equip.m4a",
		"media/shield equip.ogg",
		"media/helmet equip.m4a",
		"media/helmet equip.ogg",
		"media/armorequip.m4a",
		"media/armorequip.ogg",
		"media/bootsequip.m4a",
		"media/bootsequip.ogg",
		"media/drink.m4a",
		"media/drink.ogg",
		"media/food.m4a",
		"media/food.ogg",
		"media/amuletequip.m4a",
		"media/amuletequip.ogg",
		"media/swordhit.m4a",
		"media/swordhit.ogg",
		"media/coins2.m4a",
		"media/coins2.ogg",
		"media/openlock.m4a",
		"media/openlock.ogg",
		"media/drop.m4a",
		"media/drop.ogg",
		"media/openlock2.m4a",
		"media/openlock2.ogg",
		"media/chains gear4.m4a",
		"media/chains gear4.ogg",
		"media/chains gear5.m4a",
		"media/chains gear5.ogg",
		"media/chop wood.m4a",
		"media/chop wood.ogg",
		"media/saw wood 04.m4a",
		"media/saw wood 04.ogg",
		"media/wood1.m4a",
		"media/wood1.ogg",
		"media/woodche1.m4a",
		"media/woodche1.ogg",
		"media/woodches.m4a",
		"media/woodches.ogg",
		"media/wooddoo1.m4a",
		"media/wooddoo1.ogg",
		"media/wooddoor.m4a",
		"media/wooddoor.ogg",
		"media/woodpanel3.m4a",
		"media/woodpanel3.ogg",
		"media/woods.m4a",
		"media/woods.ogg",
		"media/woods2.m4a",
		"media/woods2.ogg",
		"media/woodwheelloop.m4a",
		"media/woodwheelloop.ogg",
		"media/evasion_001.m4a",
		"media/evasion_001.ogg",
		"media/sword.m4a",
		"media/sword.ogg",
		"media/suck pop message1_001.m4a",
		"media/suck pop message1_001.ogg",
		"media/bug.m4a",
		"media/bug.ogg",
		"media/rat.m4a",
		"media/rat.ogg",
		"media/rattle snake.m4a",
		"media/rattle snake.ogg",
		"media/bug2.m4a",
		"media/bug2.ogg",
		"media/bug3.m4a",
		"media/bug3.ogg",
		"media/money_05.m4a",
		"media/money_05.ogg",
		"media/birds_and_nature.m4a",
		"media/birds_and_nature.ogg",
		"media/rpg title.m4a",
		"media/rpg title.ogg",
		"media/night.m4a",
		"media/night.ogg",
		"media/anvil.m4a",
		"media/anvil.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}