// 
'use strict';var f=!0,g=null,h=!1;function l(){return function(){}}function x(e){return function(b){this[e]=b}}function y(e){return function(){return this[e]}}function z(e){return function(){return e}}var A={b:{},u:{}};
(function(){A.seal=function(a){return Object.seal?Object.seal(a):a};A.freeze=function(a){return Object.freeze?Object.freeze(a):a};A.fc=function(a){return"undefined"===typeof a};A.r=function(a){return"number"===typeof a};A.U=function(a){return"string"===typeof a};A.mh=function(a){return 0<a&&0===(a-1&a)};A.Tk=function(a,c){this.x=a;this.y=c;A.seal(this)};var e=A.Tk.prototype;e.offset=function(a,c){this.x+=a;this.y+=c;return this};e.tn=function(a,c){this.x*=a;this.y*=c;return this};A.re=function(a,
c,d,i,j,b,m,k){if(Math.max(a,d)<Math.min(j,m)||Math.min(a,d)>Math.max(j,m)||Math.max(c,i)<Math.min(b,k)||Math.min(c,i)>Math.max(b,k))return h;var e=j-a+m-d,o=b-c+k-i,a=d-a,c=i-c,j=m-j,b=k-b,k=Math.abs(c*j-b*a),a=a*o-c*e;return Math.abs(j*o-b*e)<=k&&Math.abs(a)<=k};A.rect=function(a,c,d,i){this.set(a,c,d,i);A.seal(this)};e=A.rect.prototype;e.set=function(a,c,d,i){this.left=a;this.top=c;this.right=d;this.bottom=i};e.width=function(){return this.right-this.left};e.height=function(){return this.bottom-
this.top};e.offset=function(a,c){this.left+=a;this.top+=c;this.right+=a;this.bottom+=c;return this};e.Xj=function(a){return!(a.right<this.left||a.bottom<this.top||a.left>this.right||a.top>this.bottom)};e.Ea=function(a,c){return a>=this.left&&a<=this.right&&c>=this.top&&c<=this.bottom};A.jc=function(){this.pa=this.oa=this.sa=this.ra=this.ya=this.xa=this.X=this.W=0;A.seal(this)};e=A.jc.prototype;e.Kf=function(a){this.W=a.left;this.X=a.top;this.xa=a.right;this.ya=a.top;this.ra=a.right;this.sa=a.bottom;
this.oa=a.left;this.pa=a.bottom};e.Sh=function(a,c){if(0===c)this.Kf(a);else{var d=Math.sin(c),i=Math.cos(c),j=a.left*d,b=a.top*d,m=a.right*d,d=a.bottom*d,k=a.left*i,e=a.top*i,o=a.right*i,i=a.bottom*i;this.W=k-b;this.X=e+j;this.xa=o-b;this.ya=e+m;this.ra=o-d;this.sa=i+m;this.oa=k-d;this.pa=i+j}};e.offset=function(a,c){this.W+=a;this.X+=c;this.xa+=a;this.ya+=c;this.ra+=a;this.sa+=c;this.oa+=a;this.pa+=c;return this};e.wg=function(a){a.left=Math.min(this.W,this.xa,this.ra,this.oa);a.top=Math.min(this.X,
this.ya,this.sa,this.pa);a.right=Math.max(this.W,this.xa,this.ra,this.oa);a.bottom=Math.max(this.X,this.ya,this.sa,this.pa)};e.Ea=function(a,c){var d=this.xa-this.W,i=this.ya-this.X,j=this.ra-this.W,b=this.sa-this.X,m=a-this.W,k=c-this.X,e=d*d+i*i,o=d*j+i*b,i=d*m+i*k,n=j*j+b*b,q=j*m+b*k,s=1/(e*n-o*o),d=(n*i-o*q)*s,e=(e*q-o*i)*s;if(0<=d&&0<e&&1>d+e)return f;d=this.oa-this.W;i=this.pa-this.X;e=d*d+i*i;o=d*j+i*b;i=d*m+i*k;s=1/(e*n-o*o);d=(n*i-o*q)*s;e=(e*q-o*i)*s;return 0<=d&&0<e&&1>d+e};e.vb=function(a,
c){a%=4;0>a&&(a+=4);switch(a){case 0:return c?this.W:this.X;case 1:return c?this.xa:this.ya;case 2:return c?this.ra:this.sa;case 3:return c?this.oa:this.pa;default:return c?this.W:this.X}};e.Ah=function(){return(this.W+this.xa+this.ra+this.oa)/4};e.Bh=function(){return(this.X+this.ya+this.sa+this.pa)/4};e.Wj=function(a){var c=a.Ah(),d=a.Bh();if(this.Ea(c,d))return f;c=this.Ah();d=this.Bh();if(a.Ea(c,d))return f;var i,j,b,m,k,e,o,n;for(o=0;4>o;o++)for(n=0;4>n;n++)if(c=this.vb(o,f),d=this.vb(o,h),i=
this.vb(o+1,f),j=this.vb(o+1,h),b=a.vb(n,f),m=a.vb(n,h),k=a.vb(n+1,f),e=a.vb(n+1,h),A.re(c,d,i,j,b,m,k,e))return f;return h};A.RGB=function(a,c,d){return Math.max(Math.min(a,255),0)|Math.max(Math.min(c,255),0)<<8|Math.max(Math.min(d,255),0)<<16};A.oi=function(a){return a&255};A.ni=function(a){return(a&65280)>>8};A.mi=function(a){return(a&16711680)>>16};A.Kn=function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])};A.Sc=function(a,c){var d,i;if(0===c)a.shift();else if(c===a.length-1)a.pop();else{for(d=
c,i=a.length-1;d<i;d++)a[d]=a[d+1];a.length=i}};A.Fd=function(a,c){var d=jQuery.inArray(c,a);0<=d&&A.Sc(a,d)};A.Da=function(a,c,d){return a<c?c:a>d?d:a};A.Q=function(a){return a/(180/Math.PI)};A.Tb=function(a){return a*(180/Math.PI)};A.Dg=function(a){a%=360;0>a&&(a+=360);return a};A.la=function(a){a%=2*Math.PI;0>a&&(a+=2*Math.PI);return a};A.Uf=function(a){return A.Dg(A.Tb(a))};A.$h=function(a){return A.la(A.Q(a))};A.Qe=function(a,c,d,i){return Math.atan2(i-c,d-a)};A.Ed=function(a,c){if(a===c)return 0;
var d=Math.sin(a),i=Math.cos(a),j=Math.sin(c),b=Math.cos(c),d=d*j+i*b;return 1<=d?0:-1>=d?Math.PI:Math.acos(d)};A.tg=function(a,c,d){var i=Math.sin(a),j=Math.cos(a),b=Math.sin(c),m=Math.cos(c);return Math.acos(i*b+j*m)>d?0<j*b-i*m?A.la(a+d):A.la(a-d):A.la(c)};A.Pc=function(a,c){var d=Math.sin(a),i=Math.cos(a),j=Math.sin(c),b=Math.cos(c);return 0>=i*j-d*b};A.Md=function(a,c,d,i){a=d-a;c=i-c;return Math.sqrt(a*a+c*c)};A.ag=function(a,c){return!a!==!c};A.uh=function(a,c,d){return a+(c-a)*d};A.gi=function(a){for(var c in a)a.hasOwnProperty(c)&&
delete a[c]};A.oc=function(){this.gc={};this.gd=0;this.wd=[];this.Uc=f;A.seal(this)};e=A.oc.prototype;e.contains=function(a){return this.gc.hasOwnProperty(a.toString())};e.add=function(a){if(!this.contains(a))this.gc[a.toString()]=a,this.gd++,this.Uc=h;return this};e.remove=function(a){if(this.contains(a))delete this.gc[a.toString()],this.gd--,this.Uc=h;return this};e.clear=function(){A.gi(this.gc);this.gd=0;this.wd.length=0;this.Uc=f;return this};e.Zj=function(){return 0===this.gd};e.Om=y("gd");
e.fi=function(){if(!this.Uc){this.wd.length=0;for(var a in this.gc)this.gc.hasOwnProperty(a)&&this.wd.push(this.gc[a]);this.Uc=f}};e.Vn=function(){this.fi();return this.wd.slice(0)};e.vd=function(){this.fi();return this.wd};A.ig=function(){this.pb=this.we=this.y=this.Ue=0;A.seal(this)};e=A.ig.prototype;e.add=function(a){this.y=a-this.Ue;this.we=this.pb+this.y;this.Ue=this.we-this.pb-this.y;this.pb=this.we};e.reset=function(){this.pb=this.we=this.y=this.Ue=0};A.Kh=function(a){return a.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,
"\\$&")};A.Fe=function(a){this.z=[];this.Lf(a);A.seal(this)};e=A.Fe.prototype;e.Lf=function(a){this.Bf=a;this.kd=a.length/2;this.z.length=a.length;this.Hd=this.Vc=-1;this.zg=0};e.pf=function(){return!this.Bf.length};e.Rh=function(a,c,d,i,j){this.z.length=8;this.kd=4;this.z[0]=a.W-c;this.z[1]=a.X-d;this.z[2]=a.xa-c;this.z[3]=a.ya-d;this.z[4]=a.ra-c;this.z[5]=a.sa-d;this.z[6]=a.oa-c;this.z[7]=a.pa-d;this.Vc=i;this.Hd=j};e.Ve=function(a,c,d){if(!(this.Vc===a&&this.Hd===c&&this.zg===d)){this.Vc=a;this.Hd=
c;this.zg=d;var i,j,b,m=0,k=1;0!==d&&(m=Math.sin(d),k=Math.cos(d));for(d=0,i=this.kd;d<i;d++)j=this.Bf[2*d]*a,b=this.Bf[2*d+1]*c,this.z[2*d]=j*k-b*m,this.z[2*d+1]=b*k+j*m}};e.Ea=function(a,c){if(a===this.z[0]&&c===this.z[1])return f;var d=5*-this.Vc-1,i=5*-this.Hd-1,j=5*this.Vc+1,b,m,k,e,o,n,q=0,s=0;for(o=0,n=this.kd;o<n;o++)b=this.z[2*o],m=this.z[2*o+1],k=this.z[2*((o+1)%n)],e=this.z[2*((o+1)%n)+1],A.re(d,i,a,c,b,m,k,e)&&q++,A.re(j,-1,a,c,b,m,k,e)&&s++;return 1===q%2||1===s%2};e.Vj=function(a,c,
d){if(this.Ea(a.z[0]+c,a.z[1]+d)||a.Ea(this.z[0]-c,this.z[1]-d))return f;var i,j,b,e,k,p,o,n,q,s,t,u;for(i=0,j=this.kd;i<j;i++){k=this.z[2*i];p=this.z[2*i+1];o=this.z[2*((i+1)%j)];n=this.z[2*((i+1)%j)+1];for(b=0,e=a.kd;b<e;b++)if(q=a.z[2*b]+c,s=a.z[2*b+1]+d,t=a.z[2*((b+1)%e)]+c,u=a.z[2*((b+1)%e)+1]+d,A.re(k,p,o,n,q,s,t,u))return f}return h};var b="lighter,xor,copy,destination-over,source-in,destination-in,source-out,destination-out,source-atop,destination-atop".split(",");A.Nd=function(a){return 0>=
a||11<=a?"source-over":b[a-1]};A.se=function(a,c,d){if(d)switch(a.Qa=d.ONE,a.Ka=d.ONE_MINUS_SRC_ALPHA,c){case 1:a.Qa=d.ONE;a.Ka=d.ONE;break;case 3:a.Qa=d.ONE;a.Ka=d.ZERO;break;case 4:a.Qa=d.ONE_MINUS_DST_ALPHA;a.Ka=d.ONE;break;case 5:a.Qa=d.DST_ALPHA;a.Ka=d.ZERO;break;case 6:a.Qa=d.ZERO;a.Ka=d.SRC_ALPHA;break;case 7:a.Qa=d.ONE_MINUS_DST_ALPHA;a.Ka=d.ZERO;break;case 8:a.Qa=d.ZERO;a.Ka=d.ONE_MINUS_SRC_ALPHA;break;case 9:a.Qa=d.DST_ALPHA;a.Ka=d.ONE_MINUS_SRC_ALPHA;break;case 10:a.Qa=d.ONE_MINUS_DST_ALPHA,
a.Ka=d.SRC_ALPHA}};A.Gn=function(a){return Math.round(1E6*a)/1E6}})();var C="undefined"!==typeof Float32Array?Float32Array:Array;function D(e){var b=new C(3);e&&(b[0]=e[0],b[1]=e[1],b[2]=e[2]);return b}function E(e){var b=new C(16);e&&(b[0]=e[0],b[1]=e[1],b[2]=e[2],b[3]=e[3],b[4]=e[4],b[5]=e[5],b[6]=e[6],b[7]=e[7],b[8]=e[8],b[9]=e[9],b[10]=e[10],b[11]=e[11],b[12]=e[12],b[13]=e[13],b[14]=e[14],b[15]=e[15]);return b}
function F(e,b){b[0]=e[0];b[1]=e[1];b[2]=e[2];b[3]=e[3];b[4]=e[4];b[5]=e[5];b[6]=e[6];b[7]=e[7];b[8]=e[8];b[9]=e[9];b[10]=e[10];b[11]=e[11];b[12]=e[12];b[13]=e[13];b[14]=e[14];b[15]=e[15]}function G(e,b){var a=b[0],c=b[1],b=b[2];e[0]*=a;e[1]*=a;e[2]*=a;e[3]*=a;e[4]*=c;e[5]*=c;e[6]*=c;e[7]*=c;e[8]*=b;e[9]*=b;e[10]*=b;e[11]*=b}
function H(e,b,a,c){c||(c=E());var d,i,j,r,m,k,p,o,n=e[0],q=e[1],e=e[2];i=a[0];j=a[1];d=a[2];a=b[1];k=b[2];n===b[0]&&q===a&&e===k?(e=c,e[0]=1,e[1]=0,e[2]=0,e[3]=0,e[4]=0,e[5]=1,e[6]=0,e[7]=0,e[8]=0,e[9]=0,e[10]=1,e[11]=0,e[12]=0,e[13]=0,e[14]=0,e[15]=1):(a=n-b[0],k=q-b[1],p=e-b[2],o=1/Math.sqrt(a*a+k*k+p*p),a*=o,k*=o,p*=o,b=j*p-d*k,d=d*a-i*p,i=i*k-j*a,(o=Math.sqrt(b*b+d*d+i*i))?(o=1/o,b*=o,d*=o,i*=o):i=d=b=0,j=k*i-p*d,r=p*b-a*i,m=a*d-k*b,(o=Math.sqrt(j*j+r*r+m*m))?(o=1/o,j*=o,r*=o,m*=o):m=r=j=0,c[0]=
b,c[1]=j,c[2]=a,c[3]=0,c[4]=d,c[5]=r,c[6]=k,c[7]=0,c[8]=i,c[9]=m,c[10]=p,c[11]=0,c[12]=-(b*n+d*q+i*e),c[13]=-(j*n+r*q+m*e),c[14]=-(a*n+k*q+p*e),c[15]=1)}
(function(){function e(a){--a;for(var d=1;32>d;d<<=1)a|=a>>d;return a+1}A.gg=function(a,d){this.q=a;var i;this.height=this.width=0;this.Ag=D([0,0,100]);this.yh=D([0,0,0]);this.di=D([0,1,0]);this.$f=D([1,1,1]);this.qh=1;this.qf=g;a.clearColor(0,0,0,0);a.clear(a.COLOR_BUFFER_BIT);a.enable(a.BLEND);a.disable(a.CULL_FACE);a.blendFunc(a.ONE,a.ONE_MINUS_SRC_ALPHA);a.disable(a.DEPTH_TEST);this.rh=a.ONE;this.oh=a.ONE_MINUS_SRC_ALPHA;this.tk=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,this.tk);this.Xf=Array(2);
this.Qf=Array(2);for(i=0;2>i;i++)this.Xf[i]=a.createBuffer(),a.bindBuffer(a.ARRAY_BUFFER,this.Xf[i]),this.Qf[i]=a.createBuffer(),a.bindBuffer(a.ARRAY_BUFFER,this.Qf[i]);this.Zc=0;this.Rj=a.createBuffer();a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,this.Rj);this.Yf=new Float32Array(16E3);this.Rf=new Float32Array(16E3);this.yn=new Float32Array(32E3);for(var j=new Uint16Array(12E3),b=i=0;12E3>i;)j[i++]=b,j[i++]=b+1,j[i++]=b+2,j[i++]=b,j[i++]=b+2,j[i++]=b+3,b+=4;a.bufferData(a.ELEMENT_ARRAY_BUFFER,j,a.STATIC_DRAW);
this.uk=this.Ya=0;this.uf=E();this.Na=E();this.ph=E();i="#ifdef GL_ES\nprecision {{precision}} float;\n#endif\nvarying vec2 vTex;\nuniform float opacity;\nuniform sampler2D sampler;\nvoid main(void) {\n\tgl_FragColor = texture2D(sampler, vTex);\n\tgl_FragColor *= opacity;\n}".replace("{{precision}}",d?"mediump":"highp");this.bf=a.createShader(a.FRAGMENT_SHADER);a.shaderSource(this.bf,i);a.compileShader(this.bf);this.Zf=a.createShader(a.VERTEX_SHADER);a.shaderSource(this.Zf,"attribute vec2 aPos;\nattribute vec2 aTex;\nvarying vec2 vTex;\nuniform mat4 matP;\nuniform mat4 matMV;\nvoid main(void) {\n\tgl_Position = matP * matMV * vec4(aPos.x, aPos.y, 0.0, 1.0);\n\tvTex = aTex;\n}");
a.compileShader(this.Zf);this.Pa=a.createProgram();a.attachShader(this.Pa,this.bf);a.attachShader(this.Pa,this.Zf);a.linkProgram(this.Pa);a.useProgram(this.Pa);this.tf=a.getAttribLocation(this.Pa,"aPos");a.enableVertexAttribArray(this.tf);this.fe=a.getAttribLocation(this.Pa,"aTex");a.enableVertexAttribArray(this.fe);this.fk=a.getUniformLocation(this.Pa,"matP");this.ek=a.getUniformLocation(this.Pa,"matMV");this.xh=a.getUniformLocation(this.Pa,"opacity");this.gk=a.getUniformLocation(this.Pa,"sampler");
a.uniform1f(this.xh,1);a.uniform1i(this.gk,0);a.activeTexture(a.TEXTURE0);a.bindTexture(a.TEXTURE_2D,g);this.wb=[];this.fb=0;this.lb=this.Ma=h;this.ae=f;this.Ti=g;this.Si=1;this.xj=a.createFramebuffer();this.Lh=g;this.Sb=D([0,0,0]);log("Max texture size: "+this.rn);log("WebGL Extensions: "+a.getSupportedExtensions());i=a.getParameter(a.ALIASED_POINT_SIZE_RANGE);this.jk=i[0];this.ik=i[1];log("Point size range: "+this.jk+" to "+this.ik);A.seal(this)};var b=A.gg.prototype;b.On=function(){if(!this.ae){var a=
this.q;this.q.useProgram(this.Pa);this.ae=f;a.enableVertexAttribArray(this.tf);a.enableVertexAttribArray(this.fe)}};b.Nn=function(){if(this.ae){var a=this.q;this.q.useProgram(this.Jn);this.ae=h;a.enableVertexAttribArray(this.kn);a.disableVertexAttribArray(this.fe)}};b.Ih=function(a,d,i){var j=[0,0,this.width,this.height],b=this.Na,e=this.uf,k=[0,0,0,0,0,0,0,0];k[0]=b[0]*a+b[4]*d+b[12];k[1]=b[1]*a+b[5]*d+b[13];k[2]=b[2]*a+b[6]*d+b[14];k[3]=b[3]*a+b[7]*d+b[15];k[4]=e[0]*k[0]+e[4]*k[1]+e[8]*k[2]+e[12]*
k[3];k[5]=e[1]*k[0]+e[5]*k[1]+e[9]*k[2]+e[13]*k[3];k[6]=e[2]*k[0]+e[6]*k[1]+e[10]*k[2]+e[14]*k[3];k[7]=-k[2];0!==k[7]&&(k[7]=1/k[7],k[4]*=k[7],k[5]*=k[7],k[6]*=k[7],i[0]=(0.5*k[4]+0.5)*j[2]+j[0],i[1]=(0.5*k[5]+0.5)*j[3]+j[1])};b.te=function(a,d){if(!(this.width===a&&this.height===d)){this.width=a;this.height=d;this.q.viewport(0,0,a,d);var i=a/d,j=this.uf,b;b=1*Math.tan(45*Math.PI/360);var i=i*b,e=-i,k=-b;j||(j=E());var p=i-e,o=b-k;j[0]=2/p;j[1]=0;j[2]=0;j[3]=0;j[4]=0;j[5]=2/o;j[6]=0;j[7]=0;j[8]=(i+
e)/p;j[9]=(b+k)/o;j[10]=-1001/999;j[11]=-1;j[12]=0;j[13]=0;j[14]=-2E3/999;j[15]=0;H(this.Ag,this.yh,this.di,this.Na);e=[0,0];i=[0,0];this.Ih(0,0,e);this.Ih(1,1,i);this.$f[0]=1/(i[0]-e[0]);this.$f[1]=-1/(i[1]-e[1]);this.q.uniformMatrix4fv(this.fk,h,this.uf)}};b.Mh=function(){H(this.Ag,this.yh,this.di,this.Na);G(this.Na,this.$f)};b.translate=function(a,d){if(!(0===a&&0===d)){this.Sb[0]=a;this.Sb[1]=d;this.Sb[2]=0;var i=this.Na,j=this.Sb,b=j[0],e=j[1],j=j[2];i[12]=i[0]*b+i[4]*e+i[8]*j+i[12];i[13]=i[1]*
b+i[5]*e+i[9]*j+i[13];i[14]=i[2]*b+i[6]*e+i[10]*j+i[14];i[15]=i[3]*b+i[7]*e+i[11]*j+i[15]}};b.scale=function(a,d){1===a&&1===d||(this.Sb[0]=a,this.Sb[1]=d,this.Sb[2]=1,G(this.Na,this.Sb))};b.yk=function(a){if(0!==a){var d=this.Na,i,j=Math.sin(a),a=Math.cos(a),b=d[0],e=d[1],k=d[2],p=d[3],o=d[4],n=d[5],q=d[6],s=d[7];i?d!==i&&(i[8]=d[8],i[9]=d[9],i[10]=d[10],i[11]=d[11],i[12]=d[12],i[13]=d[13],i[14]=d[14],i[15]=d[15]):i=d;i[0]=b*a+o*j;i[1]=e*a+n*j;i[2]=k*a+q*j;i[3]=p*a+s*j;i[4]=b*-j+o*a;i[5]=e*-j+n*
a;i[6]=k*-j+q*a;i[7]=p*-j+s*a}};b.ei=function(){for(var a=h,d=0;16>d;d++)if(this.ph[d]!==this.Na[d]){a=f;break}if(a)a=this.Mb(),a.type=5,a.wa?F(this.Na,a.wa):a.wa=E(this.Na),F(this.Na,this.ph),this.lb=this.Ma=h};A.fg=function(a,d){this.type=a;this.aa=d;this.q=d.q;this.mb=this.nd=this.wf=0;this.wa=this.Hc=g;A.seal(this)};var a=A.fg.prototype;a.Zi=function(){this.q.bindTexture(this.q.TEXTURE_2D,this.Hc);this.aa.Ti=this.Hc};a.Yi=function(){this.q.uniform1f(this.aa.xh,this.wf);this.aa.Si=this.wf};a.Vi=
function(){this.q.drawElements(this.q.TRIANGLES,this.mb,this.q.UNSIGNED_SHORT,2*this.nd)};a.Xi=function(){this.q.blendFunc(this.nd,this.mb)};a.$i=function(){this.q.uniformMatrix4fv(this.aa.ek,h,this.wa)};a.Wi=function(){var a=this.q,d=this.aa;this.Hc?(a.bindFramebuffer(a.FRAMEBUFFER,d.xj),a.framebufferTexture2D(a.FRAMEBUFFER,a.COLOR_ATTACHMENT0,a.TEXTURE_2D,this.Hc,0)):(a.framebufferTexture2D(a.FRAMEBUFFER,a.COLOR_ATTACHMENT0,a.TEXTURE_2D,g,0),a.bindFramebuffer(a.FRAMEBUFFER,g))};a.Ui=function(){this.q.clearColor(this.wa[0],
this.wa[1],this.wa[2],this.wa[3]);this.q.clear(this.q.COLOR_BUFFER_BIT)};a.Qm=l();b.Mb=function(){this.fb===this.wb.length&&this.wb.push(new A.fg(0,this));return this.wb[this.fb++]};b.Od=function(){if(0!==this.fb){var a=this.q;0<this.Ya&&(a.bindBuffer(a.ARRAY_BUFFER,this.Xf[this.Zc]),a.vertexAttribPointer(this.tf,2,a.FLOAT,h,0,0),a.bufferData(a.ARRAY_BUFFER,this.Yf.subarray(0,this.Ya),a.STREAM_DRAW),a.bindBuffer(a.ARRAY_BUFFER,this.Qf[this.Zc]),a.vertexAttribPointer(this.fe,2,a.FLOAT,h,0,0),a.bufferData(a.ARRAY_BUFFER,
this.Rf.subarray(0,this.Ya),a.STREAM_DRAW));var d,i;for(a=0,d=this.fb;a<d;a++)switch(i=this.wb[a],i.type){case 1:i.Vi();break;case 2:i.Zi();break;case 3:i.Yi();break;case 4:i.Xi();break;case 5:i.$i();break;case 6:i.Wi();break;case 7:i.Ui()}this.uk=this.Ya=this.fb=0;this.lb=this.Ma=h;this.Zc++;if(2<=this.Zc)this.Zc=0}};b.Jf=function(a){if(a!==this.qh){var d=this.Mb();d.type=3;this.qh=d.wf=a;this.lb=this.Ma=h}};b.ve=function(a){if(a!==this.qf){var d=this.Mb();d.type=2;this.qf=d.Hc=a;this.lb=this.Ma=
h}};b.If=function(a,d){if(!(a===this.rh&&d===this.oh)){var i=this.Mb();i.type=4;i.nd=a;i.mb=d;this.rh=a;this.oh=d;this.lb=this.Ma=h}};b.Ck=function(){this.If(this.q.ONE,this.q.ONE_MINUS_SRC_ALPHA)};b.jc=function(a,d,i,j,b,e,k,p){15992<=this.Ya&&this.Od();var o=this.Ya,n=this.Yf,q=this.Rf;if(this.Ma)this.wb[this.fb-1].mb+=6;else{var s=this.Mb();s.type=1;s.nd=3*(o/4);s.mb=6;this.Ma=f;this.lb=h}n[o]=a;q[o++]=0;n[o]=d;q[o++]=0;n[o]=i;q[o++]=1;n[o]=j;q[o++]=0;n[o]=b;q[o++]=1;n[o]=e;q[o++]=1;n[o]=k;q[o++]=
0;n[o]=p;q[o++]=1;this.Ya=o};b.Jh=function(a,d,i,j,b,e,k,p,o){15992<=this.Ya&&this.Od();var n=this.Ya,q=this.Yf,s=this.Rf;if(this.Ma)this.wb[this.fb-1].mb+=6;else{var t=this.Mb();t.type=1;t.nd=3*(n/4);t.mb=6;this.Ma=f;this.lb=h}q[n]=a;s[n++]=o.left;q[n]=d;s[n++]=o.top;q[n]=i;s[n++]=o.right;q[n]=j;s[n++]=o.top;q[n]=b;s[n++]=o.right;q[n]=e;s[n++]=o.bottom;q[n]=k;s[n++]=o.left;q[n]=p;s[n++]=o.bottom;this.Ya=n};b.clear=function(a,d,i,j){var b=this.Mb();b.type=7;if(!b.wa)b.wa=E();b.wa[0]=a;b.wa[1]=d;b.wa[2]=
i;b.wa[3]=j;this.lb=this.Ma=h};b.Hh=function(){this.Od();this.q.flush()};b.wh=function(a,d,i){var j=this.q,b=A.mh(a.width)&&A.mh(a.height),m=j.createTexture();j.bindTexture(j.TEXTURE_2D,m);j.pixelStorei(j.UNPACK_PREMULTIPLY_ALPHA_WEBGL,f);if(!b&&d){var k=document.createElement("canvas");k.width=e(a.width);k.height=e(a.height);k.getContext("2d").drawImage(a,0,0,a.width,a.height,0,0,k.width,k.height);j.texImage2D(j.TEXTURE_2D,0,j.RGBA,j.RGBA,j.UNSIGNED_BYTE,k)}else j.texImage2D(j.TEXTURE_2D,0,j.RGBA,
j.RGBA,j.UNSIGNED_BYTE,a);j.texParameteri(j.TEXTURE_2D,j.TEXTURE_WRAP_S,d?j.REPEAT:j.CLAMP_TO_EDGE);j.texParameteri(j.TEXTURE_2D,j.TEXTURE_WRAP_T,d?j.REPEAT:j.CLAMP_TO_EDGE);i?(j.texParameteri(j.TEXTURE_2D,j.TEXTURE_MAG_FILTER,j.LINEAR),b?(j.texParameteri(j.TEXTURE_2D,j.TEXTURE_MIN_FILTER,j.LINEAR_MIPMAP_LINEAR),j.generateMipmap(j.TEXTURE_2D)):j.texParameteri(j.TEXTURE_2D,j.TEXTURE_MIN_FILTER,j.LINEAR)):(j.texParameteri(j.TEXTURE_2D,j.TEXTURE_MAG_FILTER,j.NEAREST),j.texParameteri(j.TEXTURE_2D,j.TEXTURE_MIN_FILTER,
j.NEAREST));j.bindTexture(j.TEXTURE_2D,g);m.yg=a.width;m.xg=a.height;return m};b.Ig=function(a,d){var i=this.q,j=i.createTexture();i.bindTexture(i.TEXTURE_2D,j);i.texImage2D(i.TEXTURE_2D,0,i.RGBA,a,d,0,i.RGBA,i.UNSIGNED_BYTE,new Uint8Array(4*a*d));i.texParameteri(i.TEXTURE_2D,i.TEXTURE_WRAP_S,i.CLAMP_TO_EDGE);i.texParameteri(i.TEXTURE_2D,i.TEXTURE_WRAP_T,i.CLAMP_TO_EDGE);i.texParameteri(i.TEXTURE_2D,i.TEXTURE_MAG_FILTER,i.LINEAR);i.texParameteri(i.TEXTURE_2D,i.TEXTURE_MIN_FILTER,i.LINEAR);i.bindTexture(i.TEXTURE_2D,
g);j.yg=a;j.xg=d;return j};b.deleteTexture=function(a){this.Od();this.q.bindTexture(this.q.TEXTURE_2D,g);this.qf=g;this.q.deleteTexture(a)};b.Qh=function(a){if(a!==this.Lh){var d=this.Mb();d.type=6;this.Lh=d.Hc=a;this.lb=this.Ma=h}}})();
(function(){A.Ri=function(a){return new A.a(document.getElementById(a))};A.a=function(a){if(a&&a.getContext&&!a.c2runtime){a.c2runtime=this;this.$j="undefined"!==typeof window.device&&"undefined"!==typeof window.device.phonegap;this.dc=(this.lh="undefined"!==typeof window.AppMobi)&&"undefined"!==typeof window.c2useDirectCanvas;this.of=h;this.Yj=/android/i.test(navigator.userAgent);this.Fb=this.$j||this.lh||this.Yj;if(!this.Fb)this.Fb=/(iphone|ipod|ipad|blackberry|palm|symbian|nokia|windows\s+ce|windows\s+phone|iemobile)/i.test(navigator.userAgent);
if(!this.Fb)this.Fb=!/(windows|linux|os\s+[x9]|solaris|bsd)/i.test(navigator.userAgent);this.canvas=a;this.ja=this.aa=this.q=g;this.width=a.width;this.height=a.height;this.t=f;if(!Date.now)Date.now=function(){return+new Date};this.plugins=[];this.types={};this.C=[];this.u=[];this.zc={};this.ee=[];this.Ze={};this.ac=[];this.Ub=[];this.Be=[];this.Pe=[];this.Kd=new A.oc;this.Vk=this.yb=this.xb=0;this.sd=1;this.yc=new A.ig;this.rf=0;this.zh=f;this.ie=this.cf=this.cd=this.rd=this.ce=this.Vd=0;this.tc=
g;this.Ld=[];this.Ye=[];this.Qd=-1;this.Cf(g);this.Ac=[];this.hd=-1;this.he=0;this.sf=f;this.$e=0;this.je=new A.oc;this.ne=[];this.xe=new A.Fe([]);this.Oe={};this.Hb=this.th=this.de=this.n=g;this.yj="";this.Eb=new Image;this.Eb.src="logo.png";this.load();try{if(this.aj&&!this.Fb&&!this.dc){var c={depth:h,antialias:!this.Fb};this.q=a.getContext("webgl",c)||a.getContext("experimental-webgl",c)||a.getContext("webkit-3d",c)||a.getContext("moz-webgl",c)}}catch(d){}if(this.q)log("Using WebGL renderer"),
this.ma=document.createElement("canvas"),jQuery(this.ma).appendTo("body"),this.ma.oncontextmenu=z(h),this.ma.Fh=z(h),this.ma.width=a.width,this.ma.height=a.height,c=jQuery(this.canvas).offset(),c.position="absolute",jQuery(this.ma).css(c),this.Dc=this.ma.getContext("2d"),this.aa=new A.gg(this.q,this.Fb),this.aa.te(a.width,a.height),this.ja=g;else{if(0<this.Wg)if(this.dc)log("Using directCanvas renderer"),jQuery(this.canvas).remove(),this.canvas=document.getElementsByTagName("body")[0],document.oncontextmenu=
z(h),document.Fh=z(h),window.c2runtime=this,this.ja=new A.kl;else if("undefined"!==typeof document.getCSSCanvasContext)log("Using Canvas 2D WebKit CSS renderer"),jQuery(this.canvas).remove(),this.canvas=document.getElementsByTagName("body")[0],document.oncontextmenu=z(h),document.Fh=z(h),this.canvas.setAttribute("style","background: -webkit-canvas(c2csscanvas)"),this.ja=document.getCSSCanvasContext("2d","c2csscanvas",this.width,this.height),this.of=f,window.c2runtime=this,window.setTimeout(function(){var a=
document.getElementsByTagName("body")[0],d=document.createTextNode(" ");a.appendChild(d);a.removeChild(d)},16);if(!this.ja)log("Using Canvas 2D renderer"),this.ja=a.getContext("2d");this.Dc=this.ma=g}this.Xh=function(a){return function(){a.Ic()}}(this);this.dc?this.$g():this.go();this.G={};A.seal(this)}};var e=A.a.prototype;e.setSize=function(a,c){this.width=a;this.height=c;this.t=f;if(this.ma)this.ma.width=a,this.ma.height=c;this.aa&&this.aa.te(a,c);if(this.of)this.ja=document.getCSSCanvasContext("2d",
"c2csscanvas",this.width,this.height);this.dc&&this.ja.te(a,c)};e.load=function(){var a=A.Zg();this.name=a[0];this.Vg=a[1];this.Wg=a[11];this.kc=new A.h(this);var c,d,i,j,b,e,k,p,o,n;for(c=0,d=a[2].length;c<d;c++)k=a[2][c],A.Li(k),o=new k[0](this),o.Mf=k[1],o.nh=k[2],o.P&&o.P(),A.seal(o),this.plugins.push(o);a=A.Zg();for(c=0,d=a[3].length;c<d;c++){k=a[3][c];n=k[1];o=g;for(i=0,j=this.plugins.length;i<j;i++)if(this.plugins[i]instanceof n){o=this.plugins[i];break}n=new o.za(o);n.name=k[0];n.Gb=k[2];
n.Sk=k[3];n.Gb?(n.ge=[],n.Sd=this.$e++,n.jb=g):(n.ge=g,n.Sd=-1,n.jb=[]);n.Td=g;k[4]?(n.Sf=k[4][0],n.Tf=k[4][1]):(n.Sf=g,n.Tf=0);n.Ba=k[5]?k[5]:g;n.index=c;n.e=[];n.Jd=[];n.Qb=[new A.selection(n)];n.gb=0;n.ad=g;n.Of=f;n.Qk=A.Pk;n.Bj=A.Kk;n.Dj=A.Lk;n.v=A.Jk;n.ld=A.Nk;n.Nb=A.Ok;n.Ga=A.Mk;n.df=A.Hk;n.ef=A.Ik;n.G={};n.toString=y("name");n.u=[];for(i=0,j=k[6].length;i<j;i++){p=k[6][i];var q=p[1],s=g;for(b=0,e=this.u.length;b<e;b++)if(this.u[b]instanceof q){s=this.u[b];break}if(!s)s=new q(this),s.jd=new A.oc,
s.P&&s.P(),A.seal(s),this.u.push(s);b=new s.za(s,n);b.name=p[0];b.P();A.seal(b);n.u.push(b)}n.global=k[7];n.P();A.seal(n);n.name&&(this.types[n.name]=n);this.C.push(n);if(o.Mf)i=new o.da(n),i.Ce=this.he,this.he++,i.kf=0,i.gf=A.jh,i.toString=A.kh,i.ca=k[8],i.P(),A.seal(i),n.e.push(i)}for(c=0,d=a[4].length;c<d;c++){k=a[4][c];o=this.C[k[0]];for(i=1,j=k.length;i<j;i++)n=this.C[k[i]],n.jb.push(o),o.ge.push(n)}if(0<this.$e)for(c=0,d=this.C.length;c<d;c++)if(k=this.C[c],!k.Gb&&k.jb.length){k.Td=Array(this.$e);
n=0;for(i=0,j=k.jb.length;i<j;i++)o=k.jb[i],k.Td[o.Sd]=n,n+=o.Sk}for(c=0,d=a[5].length;c<d;c++)k=a[5][c],i=new A.ba(this,k),A.seal(i),this.zc[i.name]=i,this.ee.push(i);for(c=0,d=a[6].length;c<d;c++)k=a[6][c],i=new A.Sg(this,k),A.seal(i),this.Ze[i.name]=i,this.ac.push(i);for(c=0,d=this.ac.length;c<d;c++)this.ac[c].R();for(c=0,d=this.Be.length;c<d;c++)this.Be[c].R();delete this.Be;this.yj=a[7];this.Lb=a[8];this.le=a[9];this.ke=a[10];this.vg=1;this.aj=a[12];this.vh=a[13];this.Eg=a[14];this.Uk=a[15];
this.od=Date.now()};e.kk=function(){return this.dc?{}:new Image};e.Mi=function(){var a=0,c=0,d=f,i,j;for(i=0,j=this.Ub.length;i<j;i++){var b=this.Ub[i].Hg;if(!b||0>=b)b=5E4;a+=b;this.Ub[i].complete?c+=b:d=h}this.me=0==a?0:c/a;return d};e.go=function(){if(this.ja||this.aa){var a=this.ja||this.Dc;this.me=0;this.sh=-1;if(this.Mi())this.bh();else{if(500<=Date.now()-this.od&&this.Eb.complete&&this.sh!=this.me){a.clearRect(0,0,this.width,this.height);var c=this.width/2,d=this.height/2,i=this.Eb.width/2,
j=this.Eb.height/2;a.drawImage(this.Eb,Math.floor(c-i),Math.floor(d-j));c=Math.floor(c-i)+0.5;d=Math.floor(d+(j+12))+0.5;a.fillStyle="DodgerBlue";a.fillRect(c,d,Math.floor(this.Eb.width*this.me),6);a.strokeStyle="black";a.strokeRect(c,d,this.Eb.width,6);a.strokeStyle="white";a.strokeRect(c-1,d-1,this.Eb.width+2,8);this.sh=this.me}setTimeout(function(a){return function(){a.go()}}(this),100)}}};e.$g=function(){this.ja.Um()?(log("directCanvas: ready ("+this.width+" x "+this.height+")"),this.ja.te(this.width,
this.height),this.ja.jn(this.Ub),this.ah()):setTimeout(function(a){return function(){a.$g()}}(this),20)};e.ah=function(){var a,c,d,i,j;if(this.ja.Tm()){log("directCanvas: loaded");d=this.ja.Rm();log("directCanvas image data: "+JSON.stringify(d));for(a=0,c=this.Ub.length;a<c;a++)i=this.Ub[a],j=d[i.src],i.width=j.Wn,i.height=j.Sm,log("DC image '"+i.src+"' = "+i.width+" x "+i.height);this.bh()}else setTimeout(function(a){return function(){a.ah()}}(this),100)};e.bh=function(){this.ce=this.od=Date.now();
var a,c;for(a=0,c=this.ee.length;a<c;a++)this.ee[a].Pi();this.Vg?this.zc[this.Vg].Pf():this.ee[0].Pf();this.Ic()};var b=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame;e.Ic=function(){if(this.ma){var a=jQuery(this.canvas).offset();a.position="absolute";jQuery(this.ma).css(a)}this.hk();if(this.t&&!document.Pj)this.aa?this.hb():this.Va(),this.t=h;this.rd++;this.cd++;this.cf++;b?b(this.Xh,
this.canvas):setTimeout(this.Xh,16)};e.hk=function(){var a,c,d,i,j,b,e,k;a=Date.now();if(1E3<=a-this.ce)this.ce+=1E3,this.Vd=this.cf,this.cf=0;if(this.zh){if(0!==this.rf)if(c=a-this.rf,0===c){this.Vk++;if(10<=this.ao)this.zh=h;this.yb=1/60}else if(this.yb=c/1E3,0.5<this.yb||document.Pj)this.yb=0;else if(0.1<this.yb)this.yb=0.1;this.rf=a}this.xb=this.yb*this.sd;this.yc.add(this.xb);if(2===this.Wg)this.vg=this.width/this.height>this.le/this.ke?this.height/this.ke:this.width/this.le,this.n&&(this.n.pe(this.n.scrollX),
this.n.qe(this.n.scrollY));this.zd();this.kc.zk();for(a=0,c=this.C.length;a<c;a++)if(e=this.C[a],e.u.length)for(d=0,i=e.e.length;d<i;d++){var p=e.e[d];for(j=0,b=p.ga.length;j<b;j++)p.ga[j].Ic()}d=this.je.vd();for(a=0,c=d.length;a<c;a++)d[a].Ic();for(a=0;this.tc&&10>a++;){log("Change layout signalled to "+this.tc.name);this.n.Fk();this.tc.Pf();for(a=0,c=this.C.length;a<c;a++)if(e=this.C[a],e.global||e.Oa.Mf)for(d=0,i=e.e.length;d<i;d++)p=e.e[d],p.ok&&p.ok();this.sf=this.t=f;this.zd()}for(a=0,c=this.ac.length;a<
c;a++)this.ac[a].jf=h;this.n.Pd&&this.n.Pd.Z();this.ne.length=0;this.sf=h;for(a=0,c=this.C.length;a<c;a++)if(e=this.C[a],e.u.length)for(d=0,i=e.e.length;d<i;d++){p=e.e[d];for(j=0,b=p.ga.length;j<b;j++)k=p.ga[j],k.Wh&&k.Wh()}};e.qd=function(a){this.je.add(a)};e.Tn=function(a){this.je.remove(a)};e.Aj=function(a){return!a||-1===a.Cc?this.xb:this.yb*a.Cc};e.Va=function(){this.n.Va(this.ja);this.dc&&this.ja.Hh()};e.hb=function(){this.Dc.clearRect(0,0,this.width,this.height);this.n.hb(this.aa)};e.Ki=function(a){a&&
this.Ld.push(a)};e.Dn=function(a){A.Fd(this.Ld,a)};e.He=function(a){this.Kd.add(a)};e.zd=function(){var a,c,d,i,j,b,e,k=this.Kd.vd();for(i=0,b=k.length;i<b;i++){a=k[i];c=a.type;d=c.e;for(j=0,e=this.Ld.length;j<e;j++)this.Ld[j](a);A.Fd(d,a);if(a.o)A.Sc(a.o.e,a.kb()),a.o.Wb=f;for(j=0,e=c.jb.length;j<e;j++)A.Fd(c.jb[j].e,a);if(a.ga)for(j=0,e=a.ga.length;j<e;j++)d=a.ga[j],d.vf&&d.vf(),d.Yb.jd.remove(a);this.je.remove(a);for(j=0,e=this.kc.cb.length;j<e;j++)d=this.kc.cb[j],d.Gc.hasOwnProperty(c.index)&&
A.Fd(d.Gc[c.index],a);a.vf&&a.vf();this.ie--;32>c.Jd.length&&c.Jd.push(a)}if(!this.Kd.Zj())this.t=f;this.Kd.clear()};e.Xe=function(a,c,d,i){if(a.Gb){var j=Math.floor(Math.random()*a.ge.length);return this.Xe(a.ge[j],c,d,i)}return this.Id(a.ad,c,d,i)};e.Id=function(a,c,d,i){var j,b,e=this.C[a[1]],k=e.Oa.nh;k||(c=g);var p,o=h;e.Jd.length?(p=e.Jd.pop(),o=f,e.Oa.da.call(p,e)):p=new e.Oa.da(e);p.Ce=this.he;this.he++;p.kf=0;p.gf=A.jh;e.Of=f;var n=a[2];if(o){for(j=0,b=n.length;j<b;j++)p.L[j]=n[j];A.gi(p.G)}else p.L=
n.slice(0),p.G={};if(k)j=a[0],p.x=A.fc(d)?j[0]:d,p.y=A.fc(i)?j[1]:i,p.$n=j[2],p.width=j[3],p.height=j[4],p.depth=j[5],p.l=j[6],p.opacity=j[7],p.Wa=j[8],p.Xa=j[9],o?(p.D.set(0,0,0,0),p.qa.Kf(p.D),p.Gd.length=0):(p.D=new A.rect(0,0,0,0),p.qa=new A.jc,p.Gd=[],p.B=A.B,p.sg=A.sg,p.Ea=A.Tj,p.Ha=A.Ha,p.kb=A.Uj),p.Se=f,p.na=f,p.Cc=-1,p.o=c,p.bg=c.e.length,this.t=f;p.toString=A.kh;if(o)for(j=0,b=e.u.length;j<b;j++){var q=e.u[j],n=p.ga[j];q.Yb.da.call(n,q,p);k=a[3][j];for(d=0,i=k.length;d<i;d++)n.ca[d]=k[d];
n.P();q.Yb.jd.add(p)}else{p.ga=[];for(j=0,b=e.u.length;j<b;j++)q=e.u[j],n=new q.Yb.da(q,p),n.ca=a[3][j].slice(0),n.P(),A.seal(n),p.ga.push(n),q.Yb.jd.add(p)}k=a[4];if(o)for(j=0,b=k.length;j<b;j++)p.ca[j]=k[j];else p.ca=k.slice(0);e.e.push(p);c&&c.e.push(p);for(j=0,b=e.jb.length;j<b;j++)e.jb[j].e.push(p);this.ie++;p.P();o||A.seal(p);for(j=0,b=p.ga.length;j<b;j++)p.ga[j].vk&&p.ga[j].vk();return p};e.Yd=function(a){var c,d;for(c=0,d=this.n.M.length;c<d;c++){var i=this.n.M[c];if(i.name.toLowerCase()===
a.toLowerCase())return i}return g};e.vc=function(a){a=Math.floor(a);0>a&&(a=0);a>=this.n.M.length&&(a=this.n.M.length-1);return this.n.M[a]};e.Xd=function(a){return A.r(a)?this.vc(a):this.Yd(a.toString())};A.ba=function(a,c){this.a=a;this.Pd=g;this.scrollX=this.a.le/2;this.scrollY=this.a.ke/2;this.scale=1;this.l=0;this.name=c[0];this.width=c[1];this.height=c[2];this.ci=c[3];this.Th=c[4];var d=c[5],i,j;this.M=[];for(i=0,j=d.length;i<j;i++){var b=new A.o(this,d[i]);b.Dh=i;A.seal(b);this.M.push(b)}d=
c[6];this.cc=[];for(i=0,j=d.length;i<j;i++){var b=d[i],e=this.a.C[b[1]];if(!e.ad)e.ad=b;this.cc.push(b)}};e=A.ba.prototype;e.gh=function(){var a=this.M[0];return!a.td&&1===a.opacity&&!a.af};e.Pf=function(){if(this.Th)this.Pd=this.a.Ze[this.Th];this.a.n=this;this.scrollX=this.a.le/2;this.scrollY=this.a.ke/2;var a,c,d,i,j,b;for(a=0,d=this.a.C.length;a<d;a++){j=this.a.C[a].e;for(c=0,i=j.length;c<i;c++)if(b=j[c],b.o){var e=b.o.Dh;e>=this.M.length&&(e=this.M.length-1);b.o=this.M[e];b.o.e.push(b);b.o.Wb=
f}}for(a=0,d=this.M.length;a<d;a++)c=this.M[a],c.Qi(),c.$a=0,c.ab=0,c.bb=0,c.Za=0;for(a=0,d=this.cc.length;a<d;a++)this.a.Id(this.cc[a],g);this.a.tc=g;this.a.trigger(A.h.prototype.g.Ke,g)};e.Pi=function(){var a,c,d,i,j;for(a=0,c=0,d=this.cc.length;a<d;a++)i=this.cc[a],j=this.a.C[i[1]],j.global?this.a.Id(i,g):(this.cc[c]=i,c++);this.cc.length=c};e.Fk=function(){this.a.trigger(A.h.prototype.g.xi,g);this.a.kc.cb.length=0;var a,c,d,i,j,b;for(a=0,c=this.M.length;a<c;a++){j=this.M[a].e;for(d=0,i=j.length;d<
i;d++)b=j[d],b.type.global||this.a.He(b);this.a.zd();j.length=0;this.M[a].Wb=f}for(a=0,c=this.a.C.length;a<c;a++)if(j=this.a.C[a],!j.global&&!j.Oa.nh&&!j.Oa.Mf){for(d=0,i=j.e.length;d<i;d++)this.a.He(j.e[d]);this.a.zd()}};e.Va=function(a){this.a.Eg&&!this.gh()&&a.clearRect(0,0,this.a.width,this.a.height);var c,d;for(c=0,d=this.M.length;c<d;c++)this.M[c].na&&this.M[c].Va(a)};e.hb=function(a){this.a.Eg&&!this.gh()&&a.clear(0,0,0,0);var c,d;for(c=0,d=this.M.length;c<d;c++)this.M[c].na&&this.M[c].hb(a);
a.Hh()};e.Yg=function(){var a=this.M[0].Db(),c,d,i;for(c=1,d=this.M.length;c<d;c++)i=this.M[c],0===i.Ec&&0===i.Fc||i.Db()<a&&(a=i.Db());return a};e.pe=function(a){if(!this.ci){var c=this.a.width*(1/this.Yg())/2;a>this.width-c&&(a=this.width-c);a<c&&(a=c)}if(this.scrollX!==a)this.scrollX=a,this.a.t=f};e.qe=function(a){if(!this.ci){var c=this.a.height*(1/this.Yg())/2;a>this.height-c&&(a=this.height-c);a<c&&(a=c)}if(this.scrollY!==a)this.scrollY=a,this.a.t=f};A.o=function(a,c){this.ba=a;this.a=a.a;this.e=
[];this.scale=1;this.l=0;this.bd=h;this.rb=new A.rect(0,0,0,0);this.Zh=new A.jc;this.Za=this.bb=this.ab=this.$a=0;this.Wb=h;this.name=c[0];this.index=c[1];this.na=c[2];this.sc=c[3];this.td=c[4];this.Ec=c[5];this.Fc=c[6];this.opacity=c[7];this.af=c[8];this.eb=c[9];var d=c[10],i,j;this.wc=[];for(i=0,j=d.length;i<j;i++){var b=d[i],e=this.a.C[b[1]];if(!e.ad)e.ad=b;this.wc.push(b)}};e=A.o.prototype;e.Qi=function(){var a,c,d,i;for(a=0,c=0,d=this.wc.length;a<d;a++)i=this.a.Id(this.wc[a],this),i.type.global||
(this.wc[c]=this.wc[a],c++);this.wc.length=c};e.Rk=function(){if(this.Wb){var a,c;for(a=0,c=this.e.length;a<c;a++)this.e[a].bg=a;this.Wb=h}};e.Db=function(){return(this.scale*this.ba.scale*this.a.vg-1)*this.eb+1};e.Wd=function(){return this.bd?0:A.la(this.ba.l+this.l)};e.Va=function(a){var c=this.af||1!==this.opacity,d=this.a.canvas,i=a;if(c){if(!this.a.de)this.a.de=document.createElement("canvas"),d=this.a.de,d.width=this.a.width,d.height=this.a.height,this.a.th=d.getContext("2d");d=this.a.de;i=
this.a.th;if(d.width!==this.a.width)d.width=this.a.width;if(d.height!==this.a.height)d.height=this.a.height;this.td&&i.clearRect(0,0,this.a.width,this.a.height)}if(!this.td)i.fillStyle="rgb("+this.sc[0]+","+this.sc[1]+","+this.sc[2]+")",i.fillRect(0,0,this.a.width,this.a.height);i.save();this.bd=f;var j=this.Ca(0,0,f),b=this.Ca(0,0,h);this.bd=h;this.a.Lb&&(j=Math.round(j),b=Math.round(b));this.Nh(j,b,i);var e=this.Db();i.scale(e,e);i.translate(-j,-b);var k;for(j=0,b=this.e.length;j<b;j++)if(e=this.e[j],
e.na&&!(0===e.width||0===e.height))e.Ha(),k=e.D,k.right<this.$a||k.bottom<this.bb||k.left>this.ab||k.top>this.Za||e.Va(i);i.restore();if(c)a.globalAlpha=this.opacity,a.drawImage(d,0,0),a.globalAlpha=1};e.Nh=function(a,c,d){var i=this.Db();this.$a=a;this.bb=c;this.ab=a+this.a.width*(1/i);this.Za=c+this.a.height*(1/i);a=this.Wd();if(0!==a)d.translate(this.a.width/2,this.a.height/2),d.rotate(-a),d.translate(this.a.width/-2,this.a.height/-2),this.rb.set(this.$a,this.bb,this.ab,this.Za),this.rb.offset((this.$a+
this.ab)/-2,(this.bb+this.Za)/-2),this.Zh.Sh(this.rb,a),this.Zh.wg(this.rb),this.rb.offset((this.$a+this.ab)/2,(this.bb+this.Za)/2),this.$a=this.rb.left,this.bb=this.rb.top,this.ab=this.rb.right,this.Za=this.rb.bottom};e.hb=function(a){var c=this.a.Dc,d=this.af||1!==this.opacity;if(d){if(!this.a.Hb)this.a.Hb=a.Ig(this.a.width,this.a.height);if(this.a.Hb.yg!==this.a.width||this.a.Hb.xg!==this.a.height)a.deleteTexture(this.a.Hb),this.a.Hb=a.Ig(this.a.width,this.a.height);a.Qh(this.a.Hb);this.td&&a.clear(0,
0,0,0)}this.td||a.clear(this.sc[0]/255,this.sc[1]/255,this.sc[2]/255,1);c.save();this.bd=f;var i=this.Ca(0,0,f),j=this.Ca(0,0,h);this.bd=h;this.a.Lb&&(i=Math.round(i),j=Math.round(j));this.Nh(i,j,c);var b=this.Db();c.scale(b,b);c.translate(-i,-j);a.Mh();a.scale(b,b);a.yk(-this.Wd());a.translate((this.$a+this.ab)/-2,(this.bb+this.Za)/-2);a.ei();var e;for(i=0,j=this.e.length;i<j;i++)if(b=this.e[i],b.na&&!(0===b.width||0===b.height))b.Ha(),e=b.D,e.right<this.$a||e.bottom<this.bb||e.left>this.ab||e.top>
this.Za||b.hb(a);c.restore();d&&(a.Qh(g),a.Jf(this.opacity),a.ve(this.a.Hb),a.Ck(),a.Mh(),a.ei(),c=this.a.width/2,d=this.a.height/2,a.jc(-c,d,c,d,c,-d,-c,-d),a.ve(g))};e.Ca=function(a,c,d){var i=this.a.width/2,j=this.a.height/2,i=(this.ba.scrollX-i)*this.Ec+i,j=(this.ba.scrollY-j)*this.Fc+j,b=1/this.Db(),i=i-this.a.width*b/2,j=j-this.a.height*b/2,i=i+a*b,j=j+c*b,c=this.Wd();0!==c&&(i-=this.ba.scrollX,j-=this.ba.scrollY,a=Math.cos(c),c=Math.sin(c),b=i*a-j*c,j=j*a+i*c,i=b+this.ba.scrollX,j+=this.ba.scrollY);
return d?i:j};e.Wm=function(a,c,d){var i=this.a.width/2,j=this.a.height/2,b=(this.ba.scrollX-i)*this.Ec+i,e=(this.ba.scrollY-j)*this.Fc+j,k=1/this.Db(),b=b-this.a.width*k/2,e=e-this.a.height*k/2,b=(a-b)/k,e=(c-e)/k,c=this.Wd();0!==c&&(b-=i,e-=j,a=Math.cos(-c),c=Math.sin(-c),k=b*a-e*c,e=e*a+b*c,b=k+i,e+=j);return d?b:e}})();
(function(){A.Sg=function(a,d){this.a=a;this.ud={};this.jf=h;this.hh=new A.oc;this.name=d[0];var c=d[1];this.$b=[];var b,k;for(b=0,k=c.length;b<k;b++)this.ih(c[b],g,this.$b)};var e=A.Sg.prototype;e.toString=y("name");e.ih=function(a,d,c){switch(a[0]){case 0:a=new A.Qg(this,d,a);A.seal(a);a.bk()?this.Sj(a):c.push(a);break;case 1:a=new A.Rd(this,d,a);A.seal(a);c.push(a);break;case 2:a=new A.Rg(this,d,a),A.seal(a),c.push(a)}};e.R=function(){var a,d;for(a=0,d=this.$b.length;a<d;a++)this.$b[a].R()};e.Z=
function(){this.jf=f;var a,d;for(a=0,d=this.$b.length;a<d;a++){var c=this.$b[a];c.Z();this.a.We(c.H)}};A.selection=function(a){this.type=a;this.e=[];this.A=f};var b=A.selection.prototype;b.fh=function(){return this.A?this.type.e.length:this.e.length};b.$=function(){return this.A?this.type.e:this.e};b.xn=function(a){this.A?(this.A=h,this.e.length=1,this.e[0]=a):-1===jQuery.inArray(a,this.e)&&this.e.push(a)};b=A.a.prototype;b.We=function(a){var d,c;for(d=0,c=a.length;d<c;d++)a[d].v().A=f};b.ld=function(a){var d,
c;for(d=0,c=a.length;d<c;d++)a[d].ld()};b.Nb=function(a){var d,c;for(d=0,c=a.length;d<c;d++)a[d].Nb()};b.Ga=function(a){var d,c;for(d=0,c=a.length;d<c;d++)a[d].Ga()};A.Qg=function(a,d,c){this.sheet=a;this.parent=d;this.a=a.a;this.H=[];this.Vf=this.fd=this.Nf=h;this.ia=[];this.ub=[];this.Ra=[];c[1]?(this.dh=c[1][1].toLowerCase(),this.fd=f,c[1][0]&&(this.a.Oe[this.dh.toLowerCase()]=f)):(this.dh="",this.fd=h);var b=c[2];for(a=0,d=b.length;a<d;a++){var k=new A.Gg(this,b[a]);A.seal(k);this.ia.push(k);
this.rg(k.type)}b=c[3];for(a=0,d=b.length;a<d;a++)k=new A.action(this,b[a]),A.seal(k),this.ub.push(k);if(5===c.length){c=c[4];for(a=0,d=c.length;a<d;a++)this.sheet.ih(c[a],this,this.Ra)}};var a=A.Qg.prototype;a.R=function(){var a=this.parent;if(this.fd)for(this.Vf=f;a;){if(!a.fd){this.Vf=h;break}a=a.parent}var d;for(a=0,d=this.ia.length;a<d;a++)this.ia[a].R();for(a=0,d=this.ub.length;a<d;a++)this.ub[a].R();for(a=0,d=this.Ra.length;a<d;a++)this.Ra[a].R()};a.rg=function(a){a&&-1===jQuery.inArray(a,
this.H)&&this.H.push(a)};a.ue=function(){this.Nf=f;this.parent&&this.parent.ue()};a.bk=function(){return this.ia.length?this.ia[0].trigger:h};a.Z=function(){var a,d=this.a.ka();d.ua=this;for(d.ha=0,a=this.ia.length;d.ha<a;d.ha++)if(!this.ia[d.ha].Z())return h;this.Oh()};a.Oh=function(){var a=this.a.ka(),d;for(a.Aa=0,d=this.ub.length;a.Aa<d;a.Aa++)if(this.ub[a.Aa].Z())return;this.Ph()};a.xk=function(){var a=this.a.ka(),d;for(d=this.ub.length;a.Aa<d;a.Aa++)if(this.ub[a.Aa].Z())return;this.Ph()};a.Ph=
function(){if(this.Ra.length){var a,d,c,b,k=this.Ra.length-1;if(this.Nf)for(a=0,d=this.Ra.length;a<d;a++)c=this.Ra[a],(b=!this.Vf||!this.fd&&a<k)&&this.a.Nb(c.H),c.Z(),b?this.a.Ga(c.H):this.a.We(c.H);else for(a=0,d=this.Ra.length;a<d;a++)this.Ra[a].Z()}};a.Ak=function(){var a=this.a.ka();a.ua=this;var d;for(a.ha=0,d=this.ia.length;a.ha<d;a.ha++)if(!this.ia[a.ha].Z())return h;return f};a.Ob=function(){this.a.cd++;var a=this.a.ka().ha,d=this.a.Cf(this);for(d.ha=a+1,a=this.ia.length;d.ha<a;d.ha++)if(!this.ia[d.ha].Z()){this.a.zf();
return}this.Oh();this.a.zf()};A.Gg=function(a,d){this.Ja=a;this.sheet=a.sheet;this.a=a.a;this.w=[];this.s=[];this.G={};this.Y=d[1];this.trigger=d[3];this.nn=d[4];this.xc=d[5];this.ck=d[6];-1===d[0]?(this.type=g,this.Z=this.Hf,this.Tc=g,this.fa=-1):(this.type=this.a.C[d[0]],this.Z=this.ck?this.Bk:this.Gf,d[2]?(this.Tc=this.type.df(d[2]),this.fa=this.type.ef(d[2])):(this.Tc=g,this.fa=-1),this.Ja.parent&&this.Ja.parent.ue());if(8===d.length){var c,b,k=d[7];for(c=0,b=k.length;c<b;c++){var e=new A.xf(this,
k[c]);A.seal(e);this.w.push(e)}this.s.length=k.length}};a=A.Gg.prototype;a.R=function(){var a,d;for(a=0,d=this.w.length;a<d;a++)this.w[a].R()};a.Hf=function(){var a,d;for(a=0,d=this.w.length;a<d;a++)this.s[a]=this.w[a].get();return A.ag(this.Y.apply(this.a.kc,this.s),this.xc)};a.Bk=function(){var a,d;for(a=0,d=this.w.length;a<d;a++)this.s[a]=this.w[a].get();return this.Y.apply(this.type,this.s)};a.Gf=function(){var a,d,c,b,e,p=this.type.v();if(p.A){p.e.length=0;for(a=0,c=this.type.e.length;a<c;a++){e=
this.type.e[a];for(d=0,b=this.w.length;d<b;d++)this.s[d]=this.w[d].get(a);d=-1<this.fa?this.Y.apply(e.ga[this.fa],this.s):this.Y.apply(e,this.s);A.ag(d,this.xc)&&p.e.push(e)}p.A=h}else{var o=0;for(a=0,c=p.e.length;a<c;a++){e=p.e[a];for(d=0,b=this.w.length;d<b;d++)this.s[d]=this.w[d].get(a);d=-1<this.fa?this.Y.apply(e.ga[this.fa],this.s):this.Y.apply(e,this.s);A.ag(d,this.xc)&&(p.e[o]=e,o++)}p.e.length=o}return p.fh()};A.action=function(a,d){this.Ja=a;this.sheet=a.sheet;this.a=a.a;this.w=[];this.s=
[];this.G={};this.Y=d[1];-1===d[0]?(this.type=g,this.Z=this.Hf,this.Tc=g,this.fa=-1):(this.type=this.a.C[d[0]],this.Z=this.Gf,d[2]?(this.Tc=this.type.df(d[2]),this.fa=this.type.ef(d[2])):(this.Tc=g,this.fa=-1));if(4===d.length){var c,b,e=d[3];for(c=0,b=e.length;c<b;c++){var p=new A.xf(this,e[c]);A.seal(p);this.w.push(p)}this.s.length=e.length}};a=A.action.prototype;a.R=function(){var a,d;for(a=0,d=this.w.length;a<d;a++)this.w[a].R()};a.Hf=function(){var a,d;for(a=0,d=this.w.length;a<d;a++)this.s[a]=
this.w[a].get();return this.Y.apply(this.a.kc,this.s)};a.Gf=function(){var a=this.type.v().$(),d,c,b,e;for(d=0,b=a.length;d<b;d++){for(c=0,e=this.w.length;c<e;c++)this.s[c]=this.w[c].get(d);-1<this.fa?this.Y.apply(a[d].ga[this.fa],this.s):this.Y.apply(a[d],this.s)}return h};A.xf=function(a,d){this.hc=a;this.Ja=a.Ja;this.sheet=a.sheet;this.a=a.a;this.type=d[0];this.Ab=g;this.Pb=0;this.j=g;this.Fg=0;this.ba=g;this.key=0;this.object=g;this.index=0;this.xd="";this.Ug=this.ib=g;switch(d[0]){case 0:case 7:this.Ab=
new A.va(this,d[1]);this.Pb=0;this.get=this.Hj;this.j=new A.dd;break;case 1:this.Ab=new A.va(this,d[1]);this.Pb=0;this.get=this.Ij;this.j=new A.dd;break;case 5:this.Ab=new A.va(this,d[1]);this.Pb=0;this.get=this.Mj;this.j=new A.dd;break;case 3:case 8:this.Fg=d[1];this.get=this.Fj;break;case 6:this.ba=this.a.zc[d[1]];this.get=this.Nj;break;case 9:this.key=d[1];this.get=this.Lj;break;case 4:this.object=this.a.C[d[1]];this.get=this.Oj;this.Ja.rg(this.object);this.hc instanceof A.action?this.Ja.ue():
this.Ja.parent&&this.Ja.parent.ue();break;case 10:this.index=d[1];this.get=a.type.Gb?this.Jj:this.Kj;break;case 11:this.xd=d[1];this.ib=g;this.get=this.Gj;break;case 2:this.Ug=d[1],this.get=this.Ej}};a=A.xf.prototype;a.R=function(){if(11===this.type)this.ib=this.a.Xg(this.xd,this.Ja.parent);this.Ab&&this.Ab.R()};a.Hj=function(a){this.Pb=a||0;this.Ab.get(this.j);return this.j.data};a.Ij=function(a){this.Pb=a||0;this.Ab.get(this.j);return A.U(this.j.data)?this.j.data:""};a.Oj=y("object");a.Fj=y("Fg");
a.Mj=function(a){this.Pb=a||0;this.Ab.get(this.j);return this.j.r()?this.a.vc(this.j.data):this.a.Yd(this.j.data)};a.Nj=y("ba");a.Lj=y("key");a.Kj=y("index");a.Jj=function(a){var d=this.hc.type;return this.index+d.v().$()[a].type.Td[d.Sd]};a.Gj=y("ib");a.Ej=y("Ug");A.Rd=function(a,d,c){this.sheet=a;this.parent=d;this.a=a.a;this.H=[];this.parent||this.a.Pe.push(this);this.name=c[1];this.yd=c[2];this.data=this.mf=c[3]};a=A.Rd.prototype;a.R=l();a.Z=function(){if(this.parent)this.data=this.mf};A.Rg=function(a,
d,c){this.sheet=a;this.parent=d;this.a=a.a;this.H=[];this.$d=g;this.Qj=c[1]};a=A.Rg.prototype;a.R=function(){this.$d=this.a.Ze[this.Qj];this.sheet.hh.add(this.$d)};a.Z=function(){this.parent&&this.a.ld(this.a.C);this.$d.jf||this.$d.Z();this.parent&&this.a.Ga(this.a.C)};b.Vh=function(a,d,c,b){var e=a.v(),p,o,n,q,s;if(e.A){if(!b)e.A=h,e.e.length=0;for(p=0,n=a.e.length;p<n;p++)if(o=a.e[p],o.Ha(),q=o.o.Ca(d,c,f),s=o.o.Ca(d,c,h),o.Ea(q,s)){if(b)return h;e.e.push(o)}}else{a=0;for(p=0,n=e.e.length;p<n;p++)if(o=
e.e[p],o.Ha(),q=o.o.Ca(d,c,f),s=o.o.Ca(d,c,h),o.Ea(q,s)){if(b)return h;e.e[a]=e.e[p];a++}if(!b)e.e.length=a}return b?f:e.fh()};b.qb=function(a,d){if(!a||!d||a===d)return h;a.Ha();d.Ha();if(!a.D.Xj(d.D)||!a.qa.Wj(d.qa))return h;var c=a.ta&&!a.ta.pf(),b=d.ta&&!d.ta.pf();if(!c&&!b)return f;c?(a.ta.Ve(a.width,a.height,a.l),c=a.ta):(this.xe.Rh(a.qa,a.x,a.y,a.width,a.height),c=this.xe);b?(d.ta.Ve(d.width,d.height,d.l),b=d.ta):(this.xe.Rh(d.qa,d.x,d.y,d.width,d.height),b=this.xe);return c.Vj(b,d.x-a.x,d.y-
a.y)};b.pd=function(a){var d=g,c,b;if(!A.u.Ek)return g;for(c=0,b=this.u.length;c<b;c++)if(this.u[c]instanceof A.u.Ek){d=this.u[c];break}if(!d)return g;var e=d.jd.vd();for(c=0,b=e.length;c<b;++c)if(d=e[c],d.G.Ln&&this.qb(a,d))return d;return g};b.Gk=function(a){var d=g,c,b;if(!A.u.dk)return g;for(c=0,b=this.u.length;c<b;c++)if(this.u[c]instanceof A.u.dk){d=this.u[c];break}if(!d)return g;var e=d.jd.vd();for(c=0,b=e.length;c<b;++c)if(d=e[c],d.G.Vm&&this.qb(a,d))return d;return g};b.An=function(a,d,c,
b,e){var b=b||50,p=a.x,o=a.y,n,q=g;for(n=0;n<b;n++)if(a.x=Math.floor(p+d*n),a.y=Math.floor(o+c*n),a.B(),!this.qb(a,q)&&(q=this.pd(a),!q&&(e&&(q=this.Gk(a)),!q)))return f;a.x=p;a.y=o;a.B();return h};b.Bn=function(a,d){for(var c=A.fc(d)?100:d,b=0,e=a.x,p=a.y,o=0,n=0,q=0,s=g;b<=c;){switch(o){case 0:n=0;q=-1;b++;break;case 1:n=1;q=-1;break;case 2:n=1;q=0;break;case 3:q=n=1;break;case 4:n=0;q=1;break;case 5:n=-1;q=1;break;case 6:n=-1;q=0;break;case 7:q=n=-1}o=(o+1)%8;a.x=Math.floor(e+n*b);a.y=Math.floor(p+
q*b);a.B();if(!this.qb(a,s)&&(s=this.pd(a),!s))return f}a.x=e;a.y=p;a.B();return h};b.Cn=function(a,d){this.ne.push([a,d])};b.Oi=function(a,d){var c,b,e;for(c=0,b=this.ne.length;c<b;c++)if(e=this.ne[c],e[0]==a&&e[1]==d||e[0]==d&&e[1]==a)return f;return h};b.Nm=function(a,d,c,b){var e=a.x,p=a.y,o=Math.max(10,A.Md(d,c,e,p)),n=A.Qe(d,c,e,p),q=b||this.pd(a);if(!q)return A.la(n+Math.PI);var s=q,t,u,w,v,B=A.Q(5);for(t=1;36>t;t++)if(u=n-t*B,a.x=d+Math.cos(u)*o,a.y=c+Math.sin(u)*o,a.B(),!this.qb(a,s)&&(s=
b?g:this.pd(a),!s)){w=u;break}36===t&&(w=A.la(n+Math.PI));s=q;for(t=1;36>t;t++)if(u=n+t*B,a.x=d+Math.cos(u)*o,a.y=c+Math.sin(u)*o,a.B(),!this.qb(a,s)&&(s=b?g:this.pd(a),!s)){v=u;break}36===t&&(v=A.la(n+Math.PI));a.x=e;a.y=p;a.B();if(v===w)return v;a=A.Ed(v,w)/2;a=A.Pc(v,w)?A.la(w+a+Math.PI):A.la(v+a);w=Math.cos(n);n=Math.sin(n);v=Math.cos(a);a=Math.sin(a);d=w*v+n*a;return A.Qe(0,0,w-2*d*v,n-2*d*a)};e.Sj=function(a){this.a.Be.push(a);var d;d=a.ia[0].type?a.ia[0].type.name:"system";this.ud[d]||(this.ud[d]=
[]);d=this.ud[d];var c=a.ia[0].Y,b,e;for(b=0,e=d.length;b<e;b++)if(d[b].method==c){d[b].Tg.push(a);return}d.push({method:c,Tg:[a]})};var c=[],d=-1;b.trigger=function(a,b){if(!this.n)return h;var e=this.n.Pd;if(!e)return h;d++;d===c.length?c.push(new A.oc):c[d].clear();e=this.bi(a,b,e);d--;return e};b.bi=function(a,b,e){var m=c[d];if(m.contains(e))return h;m.add(e);var k=e.hh.vd(),m=h,p,o,n,q;for(p=0,n=k.length;p<n;p++)var s=this.bi(a,b,k[p]),m=m||s;p=b?b.type.name:"system";if(!e.ud[p])return m;k=
e.ud[p];e=g;for(p=0,n=k.length;p<n;p++)if(k[p].method==a){e=k[p].Tg;break}if(!e)return m;for(p=0,n=e.length;p<n;p++){a=e[p];this.ld(a.H);this.Cf(a);if(b)k=b.type.v(),k.A=h,k.e.length=1,k.e[0]=b;k=f;if(a.parent){s=this.ka().Uh;for(o=a.parent;o;)s.push(o),o=o.parent;s.reverse();for(o=0,q=s.length;o<q;o++)this.ld(s[o].H);for(o=0,q=s.length;o<q;o++)if(!s[o].Ak()){k=h;break}for(o=0,q=s.length;o<q;o++)this.Ga(s[o].H)}k&&(this.cd++,a.Z(),m=f);this.Ga(a.H);this.zf()}return m};A.Pg=function(){this.Uh=[];this.reset(g);
A.seal(this)};e=A.Pg.prototype;e.reset=function(a){this.ua=a;this.Aa=this.ha=0;this.Uh.length=0};e.nf=function(){return this.ua.Nf?f:this.ha<this.ua.ia.length-1?!!this.ua.H.length:h};b.uc=function(){var a=this.ka();return a.ua.ia[a.ha]};b.zj=function(){var a=this.ka();return a.ua.ub[a.Aa]};b.Cf=function(a){this.Qd++;this.Qd>=this.Ye.length&&this.Ye.push(new A.Pg);var d=this.ka();d.reset(a);return d};b.zf=function(){this.Qd--};b.ka=function(){return this.Ye[this.Qd]};b.Df=function(a){this.hd++;this.hd>=
this.Ac.length&&this.Ac.push(A.seal({name:a,index:0,Rb:h}));var d=this.ff();d.name=a;d.index=0;d.Rb=h;return d};b.Af=function(){this.hd--};b.ff=function(){return this.Ac[this.hd]};b.Xg=function(a,d){for(var c,b,e,p,o,n;d;){for(c=0,b=d.Ra.length;c<b;c++)if(n=d.Ra[c],n instanceof A.Rd&&a.toLowerCase()===n.name.toLowerCase())return n;d=d.parent}for(c=0,b=this.ac.length;c<b;c++){o=this.ac[c];for(e=0,p=o.$b.length;e<p;e++)if(n=o.$b[e],n instanceof A.Rd&&a.toLowerCase()===n.name.toLowerCase())return n}return g}})();
(function(){A.va=function(b,a){this.hc=b;this.a=b.a;this.type=a[0];this.get=[this.lj,this.hj,this.tj,this.wj,this.bj,this.uj,this.pj,this.ej,this.oj,this.sj,this.cj,this.rj,this.fj,this.qj,this.mj,this.nj,this.ij,this.jj,this.dj,this.vj,this.Og,this.kj,this.Og,this.gj][this.type];var c=g;this.j=new A.dd;this.Fa=this.w=this.s=this.Y=this.ye=this.V=this.first=this.value=g;this.fa=-1;this.nb=g;this.Wf=-1;this.Ni=g;this.xd="";this.ib=g;this.md=h;switch(this.type){case 0:case 1:case 2:this.value=a[1];
break;case 3:this.first=new A.va(b,a[1]);break;case 18:this.first=new A.va(b,a[1]);this.V=new A.va(b,a[2]);this.ye=new A.va(b,a[3]);break;case 19:this.Y=a[1];this.s=[];this.w=[];3===a.length?(c=a[2],this.s.length=c.length+1):this.s.length=1;break;case 20:this.Fa=this.a.C[a[1]];this.fa=-1;this.Y=a[2];this.md=a[3];this.nb=a[4]?new A.va(b,a[4]):g;this.s=[];this.w=[];6===a.length?(c=a[5],this.s.length=c.length+1):this.s.length=1;break;case 21:this.Fa=this.a.C[a[1]];this.md=a[2];this.nb=a[3]?new A.va(b,
a[3]):g;this.Wf=a[4];break;case 22:this.Fa=this.a.C[a[1]];this.Ni=this.Fa.df(a[2]);this.fa=this.Fa.ef(a[2]);this.Y=a[3];this.md=a[4];this.nb=a[5]?new A.va(b,a[5]):g;this.s=[];this.w=[];7===a.length?(c=a[6],this.s.length=c.length+1):this.s.length=1;break;case 23:this.xd=a[1],this.ib=g}if(4<=this.type&&17>=this.type)this.first=new A.va(b,a[1]),this.V=new A.va(b,a[2]);if(c){var d,i;for(d=0,i=c.length;d<i;d++)this.w.push(new A.va(b,c[d]))}A.seal(this)};var e=A.va.prototype;e.R=function(){if(23===this.type)this.ib=
this.hc.a.Xg(this.xd,this.hc.Ja.parent);this.first&&this.first.R();this.V&&this.V.R();this.ye&&this.ye.R();this.nb&&this.nb.R();if(this.w){var b,a;for(b=0,a=this.w.length;b<a;b++)this.w[b].R()}};e.vj=function(b){this.s[0]=b;var a;for(b=0,a=this.w.length;b<a;b++)this.w[b].get(this.j),this.s[b+1]=this.j.data;this.Y.apply(this.a.kc,this.s)};e.Og=function(b){var a=this.Fa.v().$();if(a.length){this.s[0]=b;b.Eh=this.Fa;var c;for(b=0,c=this.w.length;b<c;b++)this.w[b].get(this.j),this.s[b+1]=this.j.data;
b=this.hc.Pb;if(this.nb&&(this.nb.get(this.j),this.j.r()))b=this.j.data,a=this.Fa.e;b%=a.length;0>b&&(b+=a.length);-1<this.fa?this.Y.apply(a[b].ga[this.fa],this.s):this.Y.apply(a[b],this.s)}else this.md?b.J(""):b.p(0)};e.kj=function(b){var a=this.Fa.v().$();if(a.length){var c=this.hc.Pb;if(this.nb&&(this.nb.get(this.j),this.j.r())){c=this.j.data;a=this.Fa.e;c%=a.length;0>c&&(c+=a.length);c=a[c].L[this.Wf];A.U(c)?b.J(c):b.k(c);return}c%=a.length;0>c&&(c+=a.length);c=a[c];a=0;this.Fa.Gb&&(a=c.type.Td[this.Fa.Sd]);
c=c.L[this.Wf+a];A.U(c)?b.J(c):b.k(c)}else this.md?b.J(""):b.p(0)};e.lj=function(b){b.type=A.T.sb;b.data=this.value};e.hj=function(b){b.type=A.T.mc;b.data=this.value};e.tj=function(b){b.type=A.T.Nc;b.data=this.value};e.wj=function(b){this.first.get(b);if(b.r())b.data=-b.data};e.bj=function(b){this.first.get(b);this.V.get(this.j);b.r()&&this.j.r()&&(b.data+=this.j.data,this.j.ec()&&b.Bc())};e.uj=function(b){this.first.get(b);this.V.get(this.j);b.r()&&this.j.r()&&(b.data-=this.j.data,this.j.ec()&&b.Bc())};
e.pj=function(b){this.first.get(b);this.V.get(this.j);b.r()&&this.j.r()&&(b.data*=this.j.data,this.j.ec()&&b.Bc())};e.ej=function(b){this.first.get(b);this.V.get(this.j);b.r()&&this.j.r()&&(b.data/=this.j.data,b.Bc())};e.oj=function(b){this.first.get(b);this.V.get(this.j);b.r()&&this.j.r()&&(b.data%=this.j.data,this.j.ec()&&b.Bc())};e.sj=function(b){this.first.get(b);this.V.get(this.j);if(b.r()&&this.j.r())b.data=Math.pow(b.data,this.j.data),this.j.ec()&&b.Bc()};e.cj=function(b){this.first.get(b);
this.V.get(this.j);if(b.r())this.j.U()?b.J(b.data.toString()+this.j.data):b.data&&this.j.data?b.p(1):b.p(0);else if(b.U())b.data=this.j.U()?b.data+this.j.data:b.data+(Math.round(1E10*this.j.data)/1E10).toString()};e.rj=function(b){this.first.get(b);this.V.get(this.j);b.r()&&this.j.r()&&(b.data||this.j.data?b.p(1):b.p(0))};e.dj=function(b){this.first.get(b);b.data?this.V.get(b):this.ye.get(b)};e.fj=function(b){this.first.get(b);this.V.get(this.j);b.p(b.data===this.j.data?1:0)};e.qj=function(b){this.first.get(b);
this.V.get(this.j);b.p(b.data!==this.j.data?1:0)};e.mj=function(b){this.first.get(b);this.V.get(this.j);b.p(b.data<this.j.data?1:0)};e.nj=function(b){this.first.get(b);this.V.get(this.j);b.p(b.data<=this.j.data?1:0)};e.ij=function(b){this.first.get(b);this.V.get(this.j);b.p(b.data>this.j.data?1:0)};e.jj=function(b){this.first.get(b);this.V.get(this.j);b.p(b.data>=this.j.data?1:0)};e.gj=function(b){A.r(this.ib.data)?b.k(this.ib.data):b.J(this.ib.data)};A.dd=function(b,a){this.type=b||A.T.sb;this.data=
a||0;this.Eh=g;if(this.type==A.T.sb)this.data=Math.floor(this.data);A.seal(this)};e=A.dd.prototype;e.ak=function(){return this.type===A.T.sb};e.ec=function(){return this.type===A.T.mc};e.r=function(){return this.type===A.T.sb||this.type===A.T.mc};e.U=function(){return this.type===A.T.Nc};e.pn=function(){if(!this.ak()){if(this.ec())this.data=Math.floor(this.data);else if(this.U())this.data=parseInt(this.data,10);this.type=A.T.sb}};e.Bc=function(){if(!this.ec()){if(this.U())this.data=parseFloat(this.data);
this.type=A.T.mc}};e.qn=function(){if(!this.U())this.data=this.data.toString(),this.type=A.T.Nc};e.p=function(b){this.type=A.T.sb;this.data=Math.floor(b)};e.k=function(b){this.type=A.T.mc;this.data=b};e.J=function(b){this.type=A.T.Nc;this.data=b};e.Dk=function(b){A.r(b)?(this.type=A.T.mc,this.data=b):A.U(b)?(this.type=A.T.Nc,this.data=b.toString()):(this.type=A.T.sb,this.data=0)};A.T={sb:0,mc:1,Nc:2}})();A.h=function(e){this.a=e;this.cb=[]};
(function(){var e=A.h.prototype;e.g={};e.f={};e.d={};var b=e.g;b.li=z(f);b.Ke=z(f);b.xi=z(f);b.fl=function(a,c,d){return A.La(a,c,d)};b.il=function(a,c){var d=this.a.yc.pb;if(0===a){var b=this.a.uc();return!b.G.ji&&d>=c?b.G.ji=f:h}return A.La(d,a,c)};b.Ll=function(a){return a?a.na:h};b.Il=function(a,c,d){return!a?h:A.La(100*a.opacity,c,d)};b.mg=function(a){var c=this.a.ka(),d=c.ua,b=c.nf(),c=this.a.Df();if(b)for(b=0;b<a&&!c.Rb;b++)this.a.Nb(d.H),c.index=b,d.Ob(),this.a.Ga(d.H);else for(b=0;b<a&&!c.Rb;b++)c.index=
b,d.Ob();this.a.Af();return h};b.ol=function(a,c,d){var b=this.a.ka(),e=b.ua,b=b.nf(),a=this.a.Df(a);if(b)for(;c<=d&&!a.Rb;c++)this.a.Nb(e.H),a.index=c,e.Ob(),this.a.Ga(e.H);else for(;c<=d&&!a.Rb;c++)a.index=c,e.Ob();this.a.Af();return h};b.Ad=function(a){var c=a.v(),d=c.$().slice(0),b=this.a.ka(),e=b.ua,r=b.nf(),b=this.a.Df(name),m;if(r)for(r=0,m=d.length;r<m&&!b.Rb;r++)this.a.Nb(e.H),c=a.v(),c.A=h,c.e.length=1,c.e[0]=d[r],b.index=r,e.Ob(),this.a.Ga(e.H);else{c.A=h;c.e.length=1;for(r=0,m=d.length;r<
m&&!b.Rb;r++)c.e[0]=d[r],b.index=r,e.Ob()}this.a.Af();return h};b.Gi=function(){var a=this.a.uc(),c=a.G.Hi||0,d=this.a.rd;a.G.Hi=d;return this.a.sf||c!==d-1};b.ll=function(a){var c=this.a.uc(),d=c.G.Ie||0,b=this.a.yc.pb;if(b>=d+a){c.G.Ie=d+a;if(b>=c.G.Ie+a)c.G.Ie=b;return f}return h};b.Tl=function(a,c){if(!a)return h;var d=a.v(),b=d.$(),c=Math.floor(c);if(0>c||c>=b.length)return h;b=b[c];d.A=h;d.e.length=1;d.e[0]=b;return f};b.Ul=function(a){if(!a)return h;var a=a.v(),c=a.$(),d=Math.floor(Math.random()*
c.length);if(d>=c.length)return h;c=c[d];a.A=h;a.e.length=1;a.e[0]=c;return f};b.Kc=function(a,c,d){return A.La(a.data,c,d)};b.Je=function(a){return this.a.Oe.hasOwnProperty(a.toLowerCase())};b.Hl=function(){return"undefined"!==typeof cr_is_preview};b.Rl=function(a){return!a||!a.e.length?h:a.v().A=f};b.Cl=function(){return this.a.Fb};b=e.f;b.pl=function(a){log("Go to layout: "+a.name);this.a.tc=a};b.Lc=function(a,c,d,b){if(c&&a)a=this.a.Xe(a,c,d,b),c=a.type.v(),c.A=h,c.e.length=1,c.e[0]=a};b.sm=function(a,
c){if(a&&a.na!==c)a.na=c,this.a.t=f};b.pm=function(a,c){if(a&&(c=A.Da(c/100,0,1),a.opacity!==c))a.opacity=c,this.a.t=f};b.rm=function(a,c){if(a&&a.eb!==c)a.eb=c,this.a.t=f};b.um=function(a){if(this.a.n&&this.a.n.scale!==a)this.a.n.scale=a,this.a.t=f};b.dm=function(a){this.a.n.pe(a)};b.em=function(a){this.a.n.qe(a)};b.bm=function(a,c){this.a.n.pe(a);this.a.n.qe(c)};b.cm=function(a){if(a=a.Bj())this.a.n.pe(a.x),this.a.n.qe(a.y)};b.ea=function(a,c){if(0===a.yd)a.data=A.r(c)?c:parseFloat(c);else if(1===
a.yd)a.data=c.toString()};b.cg=function(a,c){0===a.yd?a.data=A.r(c)?a.data+c:a.data+parseFloat(c):1===a.yd&&(a.data+=c.toString())};b.Ei=function(a,c){if(0===a.yd)a.data=A.r(c)?a.data-c:a.data-parseFloat(c)};b.ng=function(a,c){var d=this.a.Oe,b=a.toLowerCase();switch(c){case 0:delete d[b];break;case 1:d[b]=f;break;case 2:d[b]?delete d[b]:d[b]=f}};b.ym=function(a){0>a&&(a=0);this.a.sd=a};b.wm=function(a,c){var d=c;0>d&&(d=0);if(a){var b=a.v().$(),e,r;for(e=0,r=b.length;e<r;e++)b[e].Cc=d}};b.Xl=function(a){if(!a)return h;
var a=a.v().$(),c,d;for(c=0,d=a.length;c<d;c++)a[c].Cc=-1};b.Jm=function(a){if(!(0>a)){var c,d,b;c=this.a.ka();var e={};e.Yh=this.a.yc.pb+a;e.Ng=c.ua;e.Aa=c.Aa+1;e.Kg=h;e.Gc={};e.H=[];for(a=0,c=this.a.C.length;a<c;a++)b=this.a.C[a],d=b.v(),d.A||(e.H.push(b),e.Gc[a.toString()]=d.e.slice(0));this.cb.push(e);return f}};b.qm=function(a,c){if(a&&a.scale!==c)a.scale=c,this.a.t=f};b.Wl=function(){var a,c,d;for(a=0,c=this.a.Pe.length;a<c;a++)d=this.a.Pe[a],d.data=d.mf};b.tm=function(a){a=A.Q(a);a=A.la(a);
if(this.a.n&&this.a.n.l!==a)this.a.n.l=a,this.a.t=f};b.om=function(a,c){if(a&&(c=A.Q(c),c=A.la(c),a.l!==c))a.l=c,this.a.t=f};b.Em=function(){if(!(0>this.a.hd))this.a.ff().Rb=f};b.ql=function(a){log("Go to layout: "+a);for(var c in this.a.zc)if(this.a.zc.hasOwnProperty(c)&&c.toLowerCase()===a.toLowerCase()){this.a.tc=this.a.zc[c];break}};b=e.d;b["int"]=function(a,c){if(A.U(c)){if(a.p(parseInt(c,10)),isNaN(a.data))a.data=0}else a.p(c)};b["float"]=function(a,c){if(A.U(c)){if(a.k(parseFloat(c)),isNaN(a.data))a.data=
0}else a.k(c)};b.Mn=function(a,c){A.U(c)?a.J(c):a.J(c.toString())};b.gn=function(a,c){a.p(c.length||0)};b.random=function(a,c,d){void 0===d?a.k(Math.random()*c):a.k(Math.random()*(d-c)+c)};b.sqrt=function(a,c){a.k(Math.sqrt(c))};b.abs=function(a,c){a.k(Math.abs(c))};b.round=function(a,c){a.p(Math.round(c))};b.floor=function(a,c){a.p(Math.floor(c))};b.ceil=function(a,c){a.p(Math.ceil(c))};b.sin=function(a,c){a.k(Math.sin(A.Q(c)))};b.cos=function(a,c){a.k(Math.cos(A.Q(c)))};b.tan=function(a,c){a.k(Math.tan(A.Q(c)))};
b.asin=function(a,c){a.k(A.Tb(Math.asin(c)))};b.acos=function(a,c){a.k(A.Tb(Math.acos(c)))};b.atan=function(a,c){a.k(A.Tb(Math.atan(c)))};b.exp=function(a,c){a.k(Math.exp(c))};b.hn=function(a,c){a.k(Math.log(c))};b.ln=function(a,c){a.k(Math.log(c)/Math.LN10)};b.max=function(a){var c=arguments[1],d,b;for(d=2,b=arguments.length;d<b;d++)c<arguments[d]&&(c=arguments[d]);a.k(c)};b.min=function(a){var c=arguments[1],d,b;for(d=2,b=arguments.length;d<b;d++)c>arguments[d]&&(c=arguments[d]);a.k(c)};b.xb=function(a){a.k(this.a.xb)};
b.sd=function(a){a.k(this.a.sd)};b.Xn=function(a){a.k((Date.now()-this.a.od)/1E3)};b.Yh=function(a){a.k(this.a.yc.pb)};b.rd=function(a){a.p(this.a.rd)};b.ie=function(a){a.p(this.a.ie)};b.Vd=function(a){a.p(this.a.Vd)};b.mn=function(a,c){if(this.a.Ac.length)if(c){var d,b;for(d=0,b=this.a.Ac.length;d<b;d++){var e=this.a.Ac[d];if(e.name===c){a.p(e.index);return}}a.p(0)}else a.p(this.a.ff().index);else a.p(0)};b.Pm=function(a,c,d,b,e){a.k(A.Md(c,d,b,e))};b.l=function(a,c,d,b,e){a.k(A.Tb(A.Qe(c,d,b,e)))};
b.Hn=function(a){a.k(this.a.n.scrollX)};b.In=function(a){a.k(this.a.n.scrollY)};b.un=function(a){a.J("\n")};b.uh=function(a,c,d,b){a.k(A.uh(c,d,b))};b.Zn=function(a){a.p(this.a.width)};b.Yn=function(a){a.p(this.a.height)};b.Un=function(a,c){a.J(c.toUpperCase())};b.on=function(a,c){a.J(c.toLowerCase())};b.Da=function(a,c,d,b){c<d?a.k(d):c>b?a.k(b):a.k(c)};b.Zm=function(a,c){var d=this.a.Xd(c);d?a.k(d.scale):a.k(0)};b.Ym=function(a,c){var d=this.a.Xd(c);d?a.k(100*d.opacity):a.k(0)};b.$m=function(a,
c){var d=this.a.Xd(c);d?a.k(d.eb):a.k(0)};b.dn=function(a){this.a.n?a.k(this.a.n.scale):a.k(0)};b.an=function(a){a.k(A.Tb(this.a.n.l))};b.Xm=function(a,c){var d=this.a.Xd(c);d?a.k(A.Tb(d.l)):a.k(0)};b.en=function(a){a.p(this.a.n.width)};b.bn=function(a){a.p(this.a.n.height)};b.find=function(a,c,d){a.p(c.search(RegExp(A.Kh(d),"i")))};b.left=function(a,c,d){a.J(c.substr(0,d))};b.right=function(a,c,d){a.J(c.substr(c.length-d))};b.sn=function(a,c,d,b){a.J(c.substr(d,b))};b.Rn=function(a,c,d,b){c=c.split(b);
d=Math.floor(d);0>d||d>=c.length?a.J(""):a.J(c[d])};b.Sn=function(a,c,d){if(!c.length)return 0;a.p(c.split(d).length)};b.replace=function(a,c,d,b){a.J(c.replace(RegExp(A.Kh(d),"gi"),b))};b.trim=function(a,c){a.J(c.trim())};b.wn=function(a){a.k(Math.PI)};b.cn=function(a){this.a.n?a.J(this.a.n.name):a.J("")};b.En=function(a){a.J(this.a.q?"webgl":this.a.dc?"directCanvas":"canvas2d")};b.Lm=function(a,c,d){a.k(A.Tb(A.Ed(A.Q(c),A.Q(d))))};b.Cg=function(a){var c=Math.floor(Math.random()*(arguments.length-
1));a.Dk(arguments[c+1])};b.Fn=function(a,c,d,b){a.p(A.RGB(c,d,b))};b.zn=function(a){a.J(this.a.Uk)};b.Mm=function(a,c,d,b){var c=A.Q(c),d=A.Q(d),e=A.Ed(c,d);A.Pc(d,c)?a.k(A.Uf(c+e*b)):a.k(A.Uf(c-e*b))};e.zk=function(){var a,c,d,b,e,r=this.a.ka();for(a=0,d=this.cb.length;a<d;a++)if(b=this.cb[a],!(b.Yh>this.a.yc.pb)){r.ua=b.Ng;r.Aa=b.Aa;r.ha=0;for(c in b.Gc)if(b.Gc.hasOwnProperty(c))e=this.a.C[parseInt(c,10)].v(),e.A=h,e.e=b.Gc[c];b.Ng.xk();this.a.We(b.H);b.Kg=f}for(a=0,c=0,d=this.cb.length;a<d;a++)b=
this.cb[a],this.cb[c]=b,b.Kg||c++;this.cb.length=c}})();
A.Li=function(e){var b=e[0].prototype,a=e[1],c=e[3],d=e[4],i=e[5],j=e[6],e=e[7];if(!b.g)b.g={};if(!b.f)b.f={};if(!b.d)b.d={};var r=b.g,m=b.f,b=b.d;if(c)r.eg=function(a,d){return A.La(this.x,a,d)},r.Ge=function(a,d){return A.La(this.y,a,d)},r.El=function(){var a=this.o;this.Ha();var d=this.D;return!(d.right<a.$a||d.bottom<a.bb||d.left>a.ab||d.top>a.Za)},r.Fl=function(){this.Ha();var a=this.D,d=this.a.n;return 0>a.right||0>a.bottom||a.left>d.width||a.top>d.height},r.Sl=function(a,d,b){var c=this.v(),
e=c.$();if(!e.length)return h;var i=e[0],j=i,m=A.Md(i.x,i.y,d,b),r,v,B;for(r=1,v=e.length;r<v;r++)if(i=e[r],B=A.Md(i.x,i.y,d,b),0===a&&B<m||1===a&&B>m)m=B,j=i;c.A=h;c.e.length=1;c.e[0]=j;return f},m.Cd=function(a){if(this.x!==a)this.x=a,this.B()},m.Dd=function(a){if(this.y!==a)this.y=a,this.B()},m.Me=function(a,d){if(this.x!==a||this.y!==d)this.x=a,this.y=d,this.B()},m.xm=function(a,d){var b=a.Dj(this);if(b){var c;b.bc?(c=b.bc(d,f),b=b.bc(d,h)):(c=b.x,b=b.y);if(this.x!==c||this.y!==b)this.x=c,this.y=
b,this.B()}},m.Ml=function(a){0!==a&&(this.x+=Math.cos(this.l)*a,this.y+=Math.sin(this.l)*a,this.B())},m.pi=function(a,d){0!==d&&(this.x+=Math.cos(A.Q(a))*d,this.y+=Math.sin(A.Q(a))*d,this.B())},b.K=function(a){a.k(this.x)},b.I=function(a){a.k(this.y)},b.xb=function(a){a.k(this.a.Aj(this))};if(d)r.ki=function(a,d){return A.La(this.width,a,d)},r.hi=function(a,d){return A.La(this.height,a,d)},m.Ne=function(a){0>a&&(a=-a);if(this.width!==a)this.width=a,this.B()},m.og=function(a){0>a&&(a=-a);if(this.height!==
a)this.height=a,this.B()},m.rc=function(a,d){var b=a,c=d;0>b&&(b=-b);0>c&&(c=-c);if(this.width!==b||this.height!==c)this.width=b,this.height=c,this.B()},b.Ia=function(a){a.k(this.width)},b.Sa=function(a){a.k(this.height)};if(i)r.$k=function(a,d){return A.Ed(this.l,A.Q(d))<=A.Q(a)},r.zl=function(a){return A.Pc(this.l,A.Q(a))},r.xl=function(a,d){var b=A.$h(d),c=A.la(this.l);return A.Pc(c,A.$h(a))&&!A.Pc(c,b)},m.fm=function(a){a=A.Q(A.Dg(a));if(!isNaN(a)&&this.l!==a)this.l=a,this.B()},m.Yl=function(a){if(0!==
a&&!isNaN(a))this.l+=A.Q(a),this.l=A.la(this.l),this.B()},m.Zl=function(a){if(0!==a&&!isNaN(a))this.l-=A.Q(a),this.l=A.la(this.l),this.B()},m.$l=function(a,d){var b=A.tg(this.l,A.Q(d),A.Q(a));if(!isNaN(b)&&this.l!==b)this.l=b,this.B()},m.am=function(a,d,b){a=A.tg(this.l,Math.atan2(b-this.y,d-this.x),A.Q(a));if(!isNaN(a)&&this.l!==a)this.l=a,this.B()},m.zm=function(a,d){var b=Math.atan2(d-this.y,a-this.x);if(!isNaN(b)&&this.l!==b)this.l=b,this.B()},b.Zk=function(a){a.k(A.Uf(this.l))};if(!a)r.ii=function(a,
d,b){return A.La(this.L[a],d,b)},r.hg=function(a){return this.L[a]},r.Ai=function(a){return this.Ce===a},m.O=function(a,d){A.r(this.L[a])?this.L[a]=A.r(d)?d:parseFloat(d):A.U(this.L[a])&&(this.L[a]=A.U(d)?d:d.toString())},m.Yk=function(a,d){A.r(this.L[a])?this.L[a]=A.r(d)?this.L[a]+d:this.L[a]+parseFloat(d):A.U(this.L[a])&&(this.L[a]=A.U(d)?this.L[a]+d:this.L[a]+d.toString())},m.Fm=function(a,d){A.r(this.L[a])&&(this.L[a]=A.r(d)?this.L[a]-d:this.L[a]-parseFloat(d))},m.qc=function(a,d){this.L[a]=d?
1:0},m.Im=function(a){this.L[a]=1-this.L[a]},m.Mc=function(){this.a.He(this)},b.jl=function(a){a.p(a.Eh.e.length)},b.qg=function(a){a.p(this.Ce)},b.rl=function(a){a.p(this.gf())};if(j)r.nc=function(){return this.na&&this.o.na},m.Di=function(a){if(!a!==!this.na)this.na=a,this.a.t=f},r.dg=function(a,d){return A.La(100*this.opacity,a,d)},m.Le=function(a){a/=100;0>a?a=0:1<a&&(a=1);if(a!==this.opacity)this.opacity=a,this.a.t=f},b.Ql=function(a){a.k(100*this.opacity)};if(e)r.Dl=function(a){return!a?h:this.o===
a},r.Vl=function(a){var d=this.v(),b=d.$();if(!b.length)return h;var c=b[0],e=c,i,j;for(i=1,j=b.length;i<j;i++)if(c=b[i],0===a){if(c.o.index>e.o.index||c.o.index===e.o.index&&c.kb()>e.kb())e=c}else if(c.o.index<e.o.index||c.o.index===e.o.index&&c.kb()<e.kb())e=c;d.A=h;d.e.length=1;d.e[0]=e;return f},m.jg=function(){var a=this.kb();if(a!==this.o.e.length-1)A.Sc(this.o.e,a),this.o.e.push(this),this.a.t=f,this.o.Wb=f},m.Nl=function(){var a=this.kb();if(0!==a)A.Sc(this.o.e,a),this.o.e.unshift(this),this.a.t=
f,this.o.Wb=f},m.Ol=function(a){if(a&&a!=this.o)A.Sc(this.o.e,this.kb()),this.o.Wb=f,this.o=a,this.bg=a.e.length,a.e.push(this),this.a.t=f},b.Kl=function(a){a.p(this.o.Dh)},b.Jl=function(a){a.J(this.o.name)},b.Km=function(a){a.p(this.kb())}};A.B=function(){this.Se=f;this.a.t=f;var e,b;for(e=0,b=this.Gd.length;e<b;e++)this.Gd[e](this)};A.sg=function(e){e&&this.Gd.push(e)};
A.Ha=function(){if(this.Se){this.D.set(this.x,this.y,this.x+this.width,this.y+this.height);this.D.offset(-this.Wa*this.width,-this.Xa*this.height);!this.l||0===this.l?this.qa.Kf(this.D):(this.D.offset(-this.x,-this.y),this.qa.Sh(this.D,this.l),this.qa.offset(this.x,this.y),this.qa.wg(this.D));var e=0;if(this.D.left>this.D.right)e=this.D.left,this.D.left=this.D.right,this.D.right=e;if(this.D.top>this.D.bottom)e=this.D.top,this.D.top=this.D.bottom,this.D.bottom=e;this.Se=h}};
A.Tj=function(e,b){if(!this.D.Ea(e,b)||!this.qa.Ea(e,b))return h;return this.ta&&!this.ta.pf()?(this.ta.Ve(this.width,this.height,this.l),this.ta.Ea(e-this.x,b-this.y)):f};A.jh=function(){this.type.Qk();return this.kf};A.Uj=function(){this.o.Rk();return this.bg};A.kh=function(){return"inst:"+this.type.name+"#"+this.Ce};A.Kk=function(){var e=this.v().$();return e.length?e[0]:g};A.Lk=function(e){var b=this.v().$();return b.length?b[e.gf()%b.length]:g};
A.Pk=function(){if(this.Of&&!this.Gb){var e,b;for(e=0,b=this.e.length;e<b;e++)this.e[e].kf=e;this.Of=h}};A.Jk=function(){return this.Qb[this.gb]};A.Nk=function(){this.gb++;this.gb===this.Qb.length?this.Qb.push(new A.selection(this)):this.Qb[this.gb].A=f};A.Ok=function(){this.gb++;this.gb===this.Qb.length&&this.Qb.push(new A.selection(this));var e=this.Qb[this.gb],b=this.Qb[this.gb-1];b.A?e.A=f:(e.A=h,e.e=b.e.slice(0))};A.Mk=function(){this.gb--};
A.Hk=function(e){var b,a;for(b=0,a=this.u.length;b<a;b++)if(e===this.u[b].name)return this.u[b];return g};A.Ik=function(e){var b,a;for(b=0,a=this.u.length;b<a;b++)if(e===this.u[b].name)return b;return-1};A.La=function(e,b,a){switch(b){case 0:return e===a;case 1:return e!==a;case 2:return e<a;case 3:return e<=a;case 4:return e>a;case 5:return e>=a;default:return h}};A.b.Ta=x("a");
(function(){var e=A.b.Ta.prototype;e.za=function(a){this.Oa=a;this.a=a.a};e.za.prototype.P=l();e.da=function(a){this.type=a;this.a=a.a;this.be=Array(256);this.Ee=Array(256);this.ze=0;this.zb=h};var b=e.da.prototype;b.P=function(){jQuery(document).keydown(function(a){return function(b){a.mk(b)}}(this));jQuery(document).keyup(function(a){return function(b){a.nk(b)}}(this))};b.mk=function(a){this.be[a.which]?this.Ee[a.which]&&a.preventDefault():(this.be[a.which]=f,this.zb=this.a.trigger(A.b.Ta.prototype.g.ti,
this),this.ze=a.which,this.a.trigger(A.b.Ta.prototype.g.vi,this),this.zb&&(this.Ee[a.which]=f,a.preventDefault()))};b.nk=function(a){this.be[a.which]=h;this.ze=a.which;this.zb=h;this.a.trigger(A.b.Ta.prototype.g.wi,this);if(this.zb||this.Ee[a.which])this.Ee[a.which]=f,a.preventDefault()};e.g={};e=e.g;e.Bd=function(a){return this.be[a]};e.vi=function(a){a=a===this.ze;this.zb=this.zb||a;return a};e.ti=z(f);e.wi=function(a){a=a===this.ze;this.zb=this.zb||a;return a}})();A.b.Ua=x("a");
(function(){var e=A.b.Ua.prototype;e.za=function(a){this.Oa=a;this.a=a.a};e.za.prototype.P=l();e.da=function(a){this.type=a;this.a=a.a;this.Te=Array(4);this.ai=this.Ae=this.Jc=this.Kb=this.Jb=0;this.hf=h};var b=e.da.prototype;b.P=function(){jQuery(document).mousemove(function(a){return function(b){a.qk(b)}}(this));jQuery(document).mousedown(function(a){return function(b){a.pk(b)}}(this));jQuery(document).mouseup(function(a){return function(b){a.rk(b)}}(this));jQuery(document).dblclick(function(a){return function(b){a.lk(b)}}(this));
var a=function(a){return function(b){a.sk(b)}}(this);document.addEventListener("mousewheel",a,h);document.addEventListener("DOMMouseScroll",a,h)};var a={left:0,top:0};b.qk=function(b){var d=this.a.of?a:jQuery(this.a.canvas).offset();this.Jb=b.pageX-d.left;this.Kb=b.pageY-d.top};b.pk=function(a){window==window.top&&a.preventDefault();this.Te[a.which]=f;this.a.trigger(A.b.Ua.prototype.g.si,this);this.Jc=a.which-1;this.Ae=0;this.a.trigger(A.b.Ua.prototype.g.kg,this);this.a.trigger(A.b.Ua.prototype.g.lg,
this)};b.rk=function(a){window==window.top&&a.preventDefault();this.Te[a.which]=h;this.Jc=a.which-1;this.a.trigger(A.b.Ua.prototype.g.yi,this)};b.lk=function(a){a.preventDefault();this.Jc=a.which-1;this.Ae=1;this.a.trigger(A.b.Ua.prototype.g.kg,this);this.a.trigger(A.b.Ua.prototype.g.lg,this)};b.sk=function(a){this.ai=0>(a.wheelDelta?a.wheelDelta:a.detail?-a.detail:0)?0:1;this.hf=h;this.a.trigger(A.b.Ua.prototype.g.zi,this);this.hf&&a.preventDefault()};e.g={};b=e.g;b.kg=function(a,d){return a===this.Jc&&
d===this.Ae};b.si=z(f);b.yl=function(a){return this.Te[a+1]};b.yi=function(a){return a===this.Jc};b.Gl=function(a){var d=this.a.uc();if(A.fc(d.G.Ch))d.G.Ch=d.xc,d.xc=h;return this.a.Vh(a,this.Jb,this.Kb,d.G.Ch)};b.lg=function(a,d,b){return a!==this.Jc||d!==this.Ae?h:this.a.Vh(b,this.Jb,this.Kb,h)};b.zi=function(a){this.hf=f;return a===this.ai};e.f={};e.f.jm=function(a){a="auto,pointer,text,crosshair,move,help,wait,none".split(",")[a];this.a.canvas.style.cursor=a;if(this.a.ma)this.a.ma.style.cursor=
a};e.d={};e=e.d;e.K=function(a,d){var b,e,r,m,k;A.fc(d)?(b=this.a.vc(0),e=b.scale,r=b.eb,m=b.Ec,k=b.l,b.scale=this.a.n.scale,b.eb=1,b.Ec=1,b.l=this.a.n.l,a.k(b.Ca(this.Jb,this.Kb,f)),b.scale=e,b.eb=r,b.Ec=m,b.l=k):(b=A.r(d)?this.a.vc(d):this.a.Yd(d))?a.k(b.Ca(this.Jb,this.Kb,f)):a.k(0)};e.I=function(a,d){var b,e,r,m,k;A.fc(d)?(b=this.a.vc(0),e=b.scale,r=b.eb,m=b.Fc,k=b.l,b.scale=this.a.n.scale,b.eb=1,b.Fc=1,b.l=this.a.n.l,a.k(b.Ca(this.Jb,this.Kb,h)),b.scale=e,b.eb=r,b.Fc=m,b.l=k):(b=A.r(d)?this.a.vc(d):
this.a.Yd(d))?a.k(b.Ca(this.Jb,this.Kb,h)):a.k(0)};e.Wk=function(a){a.k(this.Jb)};e.Xk=function(a){a.k(this.Kb)}})();A.b.c=x("a");
(function(){function e(a,b,c){var e,m=0,k,p;for(e=0,k=a.length;e<k;e++)p=a[e],p[0]===b&&p[1]===c||p[0]===c&&p[1]===b||(a[m]=a[e],m++);a.length=m}function b(a,b,c){var e,m,k;for(e=0,m=a.length;e<m;e++)if(k=a[e],k[0]===b&&k[1]===c||k[0]===c&&k[1]===b)return f;return h}var a=A.b.c.prototype;a.za=function(a){this.Oa=a;this.a=a.a};a.za.prototype.P=function(){if(!this.Gb){var a,b,c,e,m,k;for(a=0,b=this.Ba.length;a<b;a++){m=this.Ba[a];m.name=m[0];m.speed=m[1];m.loop=m[2];m.Ff=m[3];m.oe=m[4];m.Gh=m[5];m.frames=
m[6];for(c=0,e=m.frames.length;c<e;c++)k=m.frames[c],k.Sf=k[0],k.Tf=k[1],k.duration=k[2],k.Wa=k[3],k.Xa=k[4],k.lf=k[5],k.yf=k[6],k.N=this.a.kk(),k.N.src=k[0],k.N.Hg=k[1],k.Vb=g,this.a.Ub.push(k.N),A.seal(k);A.seal(m)}}};a.da=function(a){this.type=a;this.a=a.a;this.ta=new A.Fe(this.type.Ba[0].frames[0].yf)};var c=a.da.prototype;c.P=function(){this.na=0===this.ca[0];this.Zb=A.Nd(this.ca[2]);A.se(this,this.ca[2],this.a.q);this.Zd=this.ob=h;if(!(1===this.type.Ba.length&&1===this.type.Ba[0].frames.length)&&
0!==this.type.Ba[0].speed)this.a.qd(this),this.ob=f;this.F=this.type.Ba[0];this.m=this.ca[1];if(0>this.m)this.m=0;if(this.m>=this.F.frames.length)this.m=this.F.frames.length-1;if(0!==this.m){var a=this.F.frames[this.m];this.ta.Lf(a.yf);this.Wa=a.Wa;this.Xa=a.Xa}this.$c=this.type.Ba[0].speed;this.Cb=this.ed();this.Rc=f;this.Xb=0;this.Qc=f;this.Xc=this.ug="";this.Bg=0;this.Wc=-1;var b,c,e,m,k;for(a=0,b=this.type.Ba.length;a<b;a++){m=this.type.Ba[a];for(c=0,e=m.frames.length;c<e;c++)if(k=m.frames[c],
this.a.aa&&!k.Vb)k.Vb=this.a.aa.wh(k.N,h,this.a.vh)}this.Jg=this.F.frames[this.m].Vb};c.Re=function(a){this.m=a?0:this.F.frames.length-1;this.ug=this.F.name;this.Zd=f;this.a.trigger(A.b.c.prototype.g.ri,this);this.a.trigger(A.b.c.prototype.g.qi,this);this.Zd=h;if(!this.Xc.length&&-1===this.Wc)this.Rc=h;this.Xb=0};c.ed=function(){return(Date.now()-this.a.od)/1E3};c.Ic=function(){this.Xc.length&&this.Lg();0<=this.Wc&&this.Mg();var a=this.ed(),b=this.F,c=b.frames[this.m],e=c.duration/this.$c,m=this.a.sd;
if(-1!==this.Cc)m=this.Cc;e/=0===m?1.0E-9:m;if(this.Rc&&a>=this.Cb+e){this.Qc?this.m++:this.m--;this.Cb+=e;if(this.m>=b.frames.length)b.Gh?(this.Qc=h,this.m=b.frames.length-2):b.loop?this.m=b.oe:(this.Xb++,this.Xb>=b.Ff?this.Re(h):this.m=b.oe);if(0>this.m)b.Gh?(this.m=1,this.Qc=f,b.loop||(this.Xb++,this.Xb>=b.Ff&&this.Re(f))):b.loop?this.m=b.oe:(this.Xb++,this.Xb>=b.Ff?this.Re(f):this.m=b.oe);if(0>this.m)this.m=0;else if(this.m>=b.frames.length)this.m=b.frames.length-1;if(a>this.Cb+b.frames[this.m].duration/
this.$c/(0===m?1.0E-9:m))this.Cb=a;a=b.frames[this.m];this.pc(c,a);this.a.t=f}};c.Lg=function(){var a=this.F.frames[this.m],b,c,e,m=g;for(b=0,c=this.type.Ba.length;b<c;b++)if(e=this.type.Ba[b],e.name.toLowerCase()===this.Xc.toLowerCase()){m=e;break}this.Xc="";if(m&&m.name.toLowerCase()!==this.F.name.toLowerCase()){this.F=m;this.$c=m.speed;if(0>this.m)this.m=0;if(this.m>=this.F.frames.length)this.m=this.F.frames.length-1;if(1===this.Bg)this.m=0;this.Rc=f;this.Cb=this.ed();this.Qc=f;this.pc(a,this.F.frames[this.m]);
this.a.t=f}};c.Mg=function(){var a=this.F.frames[this.m],b=this.m;this.m=Math.floor(this.Wc);if(0>this.m)this.m=0;if(this.m>=this.F.frames.length)this.m=this.F.frames.length-1;if(b!==this.m)this.pc(a,this.F.frames[this.m]),this.Cb=this.ed(),this.a.t=f;this.Wc=-1};c.pc=function(a,b){var c=a.N.width,e=a.N.height,m=b.N.width,k=b.N.height;c!=m&&(this.width*=m/c);e!=k&&(this.height*=k/e);this.Wa=b.Wa;this.Xa=b.Xa;this.ta.Lf(b.yf);this.B();this.Jg=b.Vb;this.a.trigger(A.b.c.prototype.g.pc,this)};c.Va=function(a){if(1!==
this.opacity)a.globalAlpha=this.opacity;if("source-over"!==this.Zb)a.globalCompositeOperation=this.Zb;var b=this.F.frames[this.m].N,c,e;if(0===this.l&&0<=this.width&&0<=this.height)c=this.x-this.Wa*this.width,e=this.y-this.Xa*this.height,this.a.Lb&&(c=Math.round(c),e=Math.round(e)),a.drawImage(b,c,e,this.width,this.height);else{c=this.x;e=this.y;this.a.Lb&&(c=Math.round(c),e=Math.round(e));a.save();var m=0<this.width?1:-1,k=0<this.height?1:-1;a.translate(c,e);a.scale(m,k);a.rotate(this.l*m*k);a.drawImage(b,
0-this.Wa*Math.abs(this.width),0-this.Xa*Math.abs(this.height),Math.abs(this.width),Math.abs(this.height));a.restore()}if("source-over"!==this.Zb)a.globalCompositeOperation="source-over";if(1!==this.opacity)a.globalAlpha=1};c.hb=function(a){a.If(this.Qa,this.Ka);a.ve(this.Jg);a.Jf(this.opacity);var b=this.qa;if(this.a.Lb){var c=Math.round(this.x)-this.x,e=Math.round(this.y)-this.y;a.jc(b.W+c,b.X+e,b.xa+c,b.ya+e,b.ra+c,b.sa+e,b.oa+c,b.pa+e)}else a.jc(b.W,b.X,b.xa,b.ya,b.ra,b.sa,b.oa,b.pa)};c.Cj=function(a){var b=
this.F.frames[this.m],c,e;for(c=0,e=b.lf.length;c<e;c++)if(a.toLowerCase()===b.lf[c][0].toLowerCase())return c;return-1};c.bc=function(a,b){var c=this.F.frames[this.m],e=c.lf,m;m=A.U(a)?this.Cj(a):a-1;m=Math.floor(m);if(0>m||m>=e.length)return b?this.x:this.y;var k=(e[m][1]-c.Wa)*this.width,e=e[m][2],e=(e-c.Xa)*this.height,c=Math.cos(this.l);m=Math.sin(this.l);var p=k*c-e*m,e=e*c+k*m,k=p+this.x,e=e+this.y;return b?k:e};a.g={};c=a.g;c.Pl=function(a){if(!a)return h;var c=this.a,j=c.uc(),r=j.type;if(!j.G.Yc)j.G.Yc=
[],c.Ki(function(a){return function(b){var d,c=0,e,i;for(d=0,e=a.length;d<e;d++)i=a[d],i[0]!==b&&i[1]!==b&&(a[c]=a[d],c++);a.length=c}}(j.G.Yc));var m=r.v(),k=a.v(),m=m.$(),k=k.$(),p,o,n,q,s,t,u,w,v=c.ka().ua;for(p=0,o=m.length;p<o;p++){n=m[p];for(q=0,s=k.length;q<s;q++)if(t=k[q],c.qb(n,t)||c.Oi(n,t)){if(!b(j.G.Yc,n,t))j.G.Yc.push([n,t]),c.Nb(v.H),u=r.v(),w=a.v(),u.A=h,w.A=h,r===a?(u.e.length=2,u.e[0]=n,u.e[1]=t):(u.e.length=1,w.e.length=1,u.e[0]=n,w.e[0]=t),v.Ob(),c.Ga(v.H)}else e(j.G.Yc,n,t)}return h};
c.tb=function(a){if(!a)return h;var c=this.a,e=c.uc(),r=e.type,m=r.v(),k=a.v(),p=m.$(),k=k.$(),o,n,q,s,t,u;if(e.xc){r=[];for(e=0,n=p.length;e<n;e++){q=p[e];a=h;for(s=0,t=k.length;s<t;s++)if(u=k[s],c.qb(q,u)){a=f;break}a||r.push(q)}m.A=h;m.e=r;return m.e.length}var w=c.ka().ua,v=[];for(e=0,n=p.length;e<n;e++){q=p[e];for(s=0,t=k.length;s<t;s++)if(u=k[s],c.qb(q,u)){c.Nb(w.H);m=r.v();o=a.v();m.A=h;o.A=h;if(r===a)if(b(v,q,u)){c.Ga(w.H);continue}else v.push([q,u]),m.e.length=2,m.e[0]=q,m.e[1]=u;else m.e.length=
1,o.e.length=1,m.e[0]=q,o.e[0]=u;w.Ob();c.Ga(w.H)}}return h};c.wl=function(a){return this.F.name.toLowerCase()===a.toLowerCase()};c.gl=function(a,b){return A.La(this.m,a,b)};c.qi=function(a){return this.ug.toLowerCase()===a.toLowerCase()};c.ri=z(f);c.pc=z(f);c.Bl=function(){return 0>this.width};c.Al=function(){return 0>this.height};a.f={};c=a.f;c.Bm=function(a,b,c){if(a&&b){b=this.a.Xe(a,b,this.bc(c,f),this.bc(c,h));b.l=this.l;b.B();var e=this.a.zj(),c=h;if(A.fc(e.G.pg)||e.G.pg<this.a.cd)c=f,e.G.pg=
this.a.cd;a=a.v();a.A=h;c?(a.e.length=1,a.e[0]=b):a.e.push(b)}};c.Bi=function(a){this.Zb=A.Nd(a);A.se(this,a,this.a.q);this.a.t=f};c.Dm=function(){this.Rc=h};c.Cm=function(a){this.Rc=f;this.Cb=this.ed();if(1===a&&0!==this.m)a=this.F.frames[this.m],this.m=0,this.pc(a,this.F.frames[0]),this.a.t=f;if(!this.ob)this.a.qd(this),this.ob=f};c.gm=function(a,b){this.Xc=a;this.Bg=b;if(!this.ob)this.a.qd(this),this.ob=f;this.Zd||this.Lg()};c.hm=function(a){this.Wc=a;if(!this.ob)this.a.qd(this),this.ob=f;this.Zd||
this.Mg()};c.im=function(a){this.$c=Math.abs(a);this.Qc=0<=a;if(!this.ob)this.a.qd(this),this.ob=f};c.vm=function(a){a=Math.abs(this.width)*(0===a?-1:1);if(this.width!==a)this.width=a,this.B()};c.km=function(a){a=Math.abs(this.height)*(0===a?-1:1);if(this.height!==a)this.height=a,this.B()};a.d={};a=a.d;a.al=function(a){a.p(this.m)};a.bl=function(a){a.p(this.F.frames.length)};a.cl=function(a){a.J(this.F.name)};a.dl=function(a){a.k(this.$c)};a.tl=function(a,b){a.k(this.bc(b,f))};a.ul=function(a,b){a.k(this.bc(b,
h))};a.vl=function(a){a.k(this.F.frames[this.m].N.width)};a.sl=function(a){a.k(this.F.frames[this.m].N.height)}})();A.b.Oc=x("a");
(function(){var e=A.b.Oc.prototype;e.P=function(){e.f.Ne=function(a){if(this.width!==a)this.width=a,this.lc=f,this.B()}};e.za=function(a){this.Oa=a;this.a=a.a};e.za.prototype.P=l();e.da=function(a){this.type=a;this.a=a.a;this.Ib=[];this.lc=f};var b=e.da.prototype,a={};b.P=function(){this.text=this.ca[0];this.na=0===this.ca[1];this.font=this.ca[2];this.color=this.ca[3];this.eh=this.ca[4];this.Ud=this.Bb="";var a=this.font.split(" ");this.Pn=this.Qn=this.ic=0;var b;for(b=0;b<a.length;b++)if("pt"===
a[b].substr(a[b].length-2,2)){this.ic=parseInt(a[b].substr(0,a[b].length-2));this.Ef=Math.ceil(96*(this.ic/72))+4;this.Bb=a[b+1];if(0<b)this.Ud=a[b-1];break}};b.De=function(){this.font=this.Ud+" "+this.ic.toString()+"pt "+this.Bb;this.lc=f;this.a.t=f};b.Va=function(a){a.font=this.font;a.textBaseline="top";a.fillStyle=this.color;if(1!==this.opacity)a.globalAlpha=this.opacity;if(this.lc)this.type.Oa.Ii(this.text,this.Ib,a,this.width),this.lc=h;this.Ha();var b=this.qa.W,c=this.qa.X;this.a.Lb&&(b=Math.round(b),
c=Math.round(c));0!==this.l&&(a.save(),a.translate(b,c),a.rotate(this.l),c=b=0);var e=c+this.height,m=this.Ef,k,p;for(p=0;p<this.Ib.length&&!(k=b,1===this.eh?k=b+(this.width-this.Ib[p].width)/2:2===this.eh&&(k=b+(this.width-this.Ib[p].width)),a.fillText(this.Ib[p].text,k,c),c+=m,c>=e-m);p++);0!==this.l&&a.restore();if(1!==this.opacity)a.globalAlpha=1};b.hb=function(){var a=this.opacity;this.opacity*=this.o.opacity;this.a.Dc&&this.Va(this.a.Dc);this.opacity=a};var c=[];e.Fi=function(a){c.length=0;
for(var b="",e,r=0;r<a.length;)if(e=a.charAt(r),"\n"===e)b.length&&(c.push(b),b=""),c.push("\n"),++r;else if(" "===e||"\t"===e||"-"===e){do b+=a.charAt(r),r++;while(r<a.length&&(" "===a.charAt(r)||"\t"===a.charAt(r)));c.push(b);b=""}else r<a.length&&(b+=e,r++);b.length&&c.push(b)};e.Ii=function(a,b,c,e){if(!a||!a.length)b.length=0;else if(2>=e)b.length=0;else{if(100>=a.length&&-1===a.indexOf("\n")){var m=c.measureText(a).width;if(m<=e){b.length?b.length=1:b.push({});b[0].text=a;b[0].width=m;return}}this.Ji(a,
b,c,e)}};e.Ji=function(a,b,e,r){this.Fi(a);var a="",m,k,p,o=0;for(p=0;p<c.length;p++)if("\n"===c[p])o>=b.length&&b.push({}),k=b[o],k.text=a,k.width=e.measureText(a).width,o++,a="";else if(m=a,a+=c[p],k=e.measureText(a).width,k>=r)o>=b.length&&b.push({}),k=b[o],k.text=m,k.width=e.measureText(m).width,o++,a=c[p];if(a.length)o>=b.length&&b.push({}),k=b[o],k.text=a,k.width=e.measureText(a).width,o++;b.length=o};e.g={};e.g.hl=function(a,b){return b?this.text==a:this.text.toLowerCase()==a.toLowerCase()};
e.f={};b=e.f;b.Ci=function(a){A.r(a)&&(a=Math.round(1E10*a)/1E10);a=a.toString();if(this.text!==a)this.text=a,this.lc=f,this.a.t=f};b.el=function(a){A.r(a)&&(a=Math.round(1E10*a)/1E10);if(a=a.toString())this.text+=a,this.lc=f,this.a.t=f};b.mm=function(a,b){var c="";switch(b){case 1:c="bold";break;case 2:c="italic";break;case 3:c="bold italic"}if(!(a===this.Bb&&c===this.Ud))this.Bb=a,this.Ud=c,this.De()};b.nm=function(a){if(this.ic!==a)this.ic=a,this.Ef=Math.ceil(96*(this.ic/72))+4,this.De()};b.lm=
function(a){a="rgb("+A.oi(a).toString()+","+A.ni(a).toString()+","+A.mi(a).toString()+")";if(a!==this.color)this.color=a,this.a.t=f};b.Am=function(b,c){if(a.hasOwnProperty(c)){var e="'"+b+"'";if(this.Bb!==e)this.Bb=e,this.De()}else{e=document.createElement("link");e.href=c;e.rel="stylesheet";e.type="text/css";var r=function(a){return function(){a.a.t=f;a.lc=f}}(this);e.onload=r;for(var m=1;10>m;m++)setTimeout(r,100*m),setTimeout(r,1E3*m);document.getElementsByTagName("head")[0].appendChild(e);a[c]=
f;this.Bb="'"+b+"'";this.De();log("Requesting web font '"+c+"'... (tick "+this.a.rd.toString()+")")}};e.d={};b=e.d;b.Oc=function(a){a.J(this.text)};b.ml=function(a){a.J(this.Bb)};b.nl=function(a){a.p(this.ic)};b.Hm=function(a){var b=0,c,e,m;for(c=0,e=this.Ib.length;c<e;c++)m=this.Ib[c].width,b<m&&(b=m);a.p(b)};b.Gm=function(a){a.p(this.Ib.length*this.Ef)}})();A.b.i=x("a");
(function(){var e=A.b.i.prototype;e.za=function(a){this.Oa=a;this.a=a.a};e.za.prototype.P=function(){if(!this.Gb)this.N=new Image,this.N.src=this.Sf,this.N.Hg=this.Tf,this.a.Ub.push(this.N),this.Vb=this.pattern=g};e.da=function(a){this.type=a;this.a=a.a};var b=e.da.prototype;b.P=function(){this.na=0===this.ca[0];this.Zb=A.Nd(this.ca[1]);A.se(this,this.ca[1],this.a.q);this.wk=new A.rect(0,0,0,0);if(this.a.aa&&!this.type.Vb)this.type.Vb=this.a.aa.wh(this.type.N,f,this.a.vh)};b.Va=function(a){if(!this.type.pattern)this.type.pattern=
a.createPattern(this.type.N,"repeat");a.save();a.globalAlpha=this.opacity;a.globalCompositeOperation=this.Zb;a.fillStyle=this.type.pattern;var b=this.x,d=this.y;this.a.Lb&&(b=Math.round(b),d=Math.round(d));var e=-(this.Wa*this.width),j=-(this.Xa*this.height),r=e%this.type.N.width,m=j%this.type.N.height;0>r&&(r+=this.type.N.width);0>m&&(m+=this.type.N.height);a.translate(b,d);a.rotate(this.l);a.translate(r,m);a.fillRect(e-r,j-m,this.width,this.height);a.restore()};b.hb=function(a){a.If(this.Qa,this.Ka);
a.ve(this.type.Vb);a.Jf(this.opacity);var b=this.wk;b.right=this.width/this.type.N.width;b.bottom=this.height/this.type.N.height;var d=this.qa;if(this.a.Lb){var e=Math.round(this.x)-this.x,j=Math.round(this.y)-this.y;a.Jh(d.W+e,d.X+j,d.xa+e,d.ya+j,d.ra+e,d.sa+j,d.oa+e,d.pa+j,b)}else a.Jh(d.W,d.X,d.xa,d.ya,d.ra,d.sa,d.oa,d.pa,b)};e.g={};e.f={};e.f.Bi=function(a){this.Zb=A.Nd(a);A.se(this,a,this.a.q);this.a.t=f};e.d={}})();A.u.bound=x("a");
(function(){var e=A.u.bound.prototype;e.za=function(b,a){this.Yb=b;this.vn=a;this.a=b.a};e.za.prototype.P=l();e.da=function(b,a){this.type=b;this.Yb=b.Yb;this.S=a;this.a=b.a;this.mode=0};e=e.da.prototype;e.P=function(){this.mode=this.ca[0]};e.Ic=l();e.Wh=function(){this.S.Ha();var b=this.S.D,a=this.S.o.ba,c=h;if(0===this.mode){if(0>this.S.x)this.S.x=0,c=f;if(0>this.S.y)this.S.y=0,c=f;if(this.S.x>a.width)this.S.x=a.width,c=f;if(this.S.y>a.height)this.S.y=a.height,c=f}else 0>b.left&&(this.S.x-=b.left,
c=f),0>b.top&&(this.S.y-=b.top,c=f),b.right>a.width&&(this.S.x-=b.right-a.width,c=f),b.bottom>a.height&&(this.S.y-=b.bottom-a.height,c=f);c&&this.S.B()}})();
A.Zg=function(){return[g,"Layout 1",[[A.b.Ta,f,h,h,h,h,h,h],[A.b.Ua,f,h,h,h,h,h,h],[A.b.c,h,f,f,f,f,f,f],[A.b.Oc,h,f,f,f,f,f,f],[A.b.i,h,f,f,f,f,f,f]],[["t0",A.b.c,h,1,g,[["Default",5,h,1,0,h,[["images/sprite-default-000.png",93,1,0,0,[],[]]]]],[],h],["t1",A.b.i,h,4,["images/neg.png",93],g,[],h],["t2",A.b.Oc,h,0,g,g,[],h],["t3",A.b.Ua,h,0,g,g,[],h,[]],["t4",A.b.c,h,2,g,[["Default",5,h,1,0,h,[["images/ball-default-000.png",881,1,0.5,0.5,[],[]]]]],[],h],["t5",A.b.i,h,0,["images/boundary.png",93],g,
[],h],["t6",A.b.c,h,6,g,[["Default",5,h,1,0,h,[["images/player-default-000.png",723,1,0,0,[],[]]]]],[["BoundToLayout",A.u.bound]],h],["t7",A.b.Ta,h,0,g,g,[],h,[]],["t8",A.b.c,h,0,g,[["Default",5,h,1,0,h,[["images/cmlh9ak-default-000.png",687895,1,0.5,0.501502,[],[]]]]],[],h],["t9",A.b.c,f,0,g,g,[],h],["t10",A.b.i,f,0,g,g,[],h]],[[9,0],[10,5,1]],[["Layout 1",640,480,h,"Event sheet 1",[["Layer 2",0,f,[255,255,255],h,1,1,1,h,1,[[[320,240.048,0,576,440,0,0,1,0.5,0.501502],8,[],[],[0,0,0]]]],["Layer 0",
1,f,[255,255,255],f,1,1,1,h,1,[[[32,32,0,576,416,0,0,1,0,0],0,[0],[],[0,0,0]],[[256,544,0,16,16,0,0,1,0,0],1,[0,0,0,0],[],[0,0,0]],[[0,0,0,608,32,0,0,0.5,0,0],5,[],[],[1,0,0]],[[32,448,0,608,32,0,0,0.5,0,0],5,[],[],[1,0,0]],[[0,32,0,32,448,0,0,0.5,0,0],5,[],[],[1,0,0]],[[608,0,0,32,448,0,0,0.5,0,0],5,[],[],[1,0,0]]]],["Layer 1",2,f,[255,255,255],f,1,1,1,h,1,[[[96,224,0,16,16,0,0,1,0.5,0.5],4,[1,1],[],[0,0,0]],[[256,449,0,14,14,0,0,1,0,0],6,[0,0,-1,0,0,0],[[1]],[0,0,0]],[[480,224,0,16,16,0,0,1,0.5,
0.5],4,[1,1],[],[0,0,0]],[[0,-1,0,288,32,0,0,1,0,0],2,[],[],["Text",0,"12pt Arial","rgb(0,0,0)",0,0]]]]],[]]],[["Event sheet 1",[[0,g,[[-1,A.h.prototype.g.Ke,g,f,h,h,h]],[[1,A.b.i.prototype.f.Mc,g]]],[1,"die",0,0],[1,"tomove",0,0],[0,[f,"ball"],[[-1,A.h.prototype.g.Je,g,h,h,h,h,[[1,[2,"ball"]]]]],[],[[0,g,[[-1,A.h.prototype.g.Ke,g,f,h,h,h]],[[4,A.b.c.prototype.f.O,g,[[10,0],[7,[19,A.h.prototype.d.Cg,[[0,-1],[0,1]]]]]],[4,A.b.c.prototype.f.O,g,[[10,1],[7,[19,A.h.prototype.d.Cg,[[0,-1],[0,1]]]]]]]],
[0,g,[],[[-1,A.h.prototype.f.cg,g,[[11,"tomove"],[7,[6,[0,100],[19,A.h.prototype.d.xb]]]]]]],[0,g,[[-1,A.h.prototype.g.mg,g,h,f,h,h,[[0,[23,"tomove"]]]],[-1,A.h.prototype.g.Ad,g,h,f,h,h,[[4,4]]]],[],[[1,"bx",0,0],[1,"by",0,0],[0,g,[],[[4,A.b.c.prototype.f.Cd,g,[[0,[4,[20,4,A.b.c.prototype.d.K,h,g],[21,4,h,g,0]]]]]]],[0,g,[[4,A.b.c.prototype.g.tb,g,h,h,h,f,[[4,10]]]],[],[[0,g,[[10,A.b.i.prototype.g.nc,g,h,h,h,h]],[[-1,A.h.prototype.f.ea,g,[[11,"die"],[7,[0,1]]]]]],[0,g,[[10,A.b.i.prototype.g.nc,g,
h,h,f,h]],[[-1,A.h.prototype.f.ea,g,[[11,"bx"],[7,[0,1]]]]]]]],[0,g,[],[[4,A.b.c.prototype.f.Cd,g,[[0,[5,[20,4,A.b.c.prototype.d.K,h,g],[21,4,h,g,0]]]]],[4,A.b.c.prototype.f.Dd,g,[[0,[4,[20,4,A.b.c.prototype.d.I,h,g],[21,4,h,g,1]]]]]]],[0,g,[[4,A.b.c.prototype.g.tb,g,h,h,h,f,[[4,10]]]],[],[[0,g,[[10,A.b.i.prototype.g.nc,g,h,h,h,h]],[[-1,A.h.prototype.f.ea,g,[[11,"die"],[7,[0,1]]]]]],[0,g,[[10,A.b.i.prototype.g.nc,g,h,h,f,h]],[[-1,A.h.prototype.f.ea,g,[[11,"by"],[7,[0,1]]]]]]]],[0,g,[],[[4,A.b.c.prototype.f.Dd,
g,[[0,[5,[20,4,A.b.c.prototype.d.I,h,g],[21,4,h,g,1]]]]]]],[0,g,[[-1,A.h.prototype.g.Kc,g,h,h,h,h,[[11,"bx"],[8,0],[7,[0,1]]]]],[[4,A.b.c.prototype.f.O,g,[[10,0],[7,[3,[21,4,h,g,0]]]]]]],[0,g,[[-1,A.h.prototype.g.Kc,g,h,h,h,h,[[11,"by"],[8,0],[7,[0,1]]]]],[[4,A.b.c.prototype.f.O,g,[[10,1],[7,[3,[21,4,h,g,1]]]]]]],[0,g,[],[[4,A.b.c.prototype.f.Cd,g,[[0,[4,[20,4,A.b.c.prototype.d.K,h,g],[21,4,h,g,0]]]]],[4,A.b.c.prototype.f.Dd,g,[[0,[4,[20,4,A.b.c.prototype.d.I,h,g],[21,4,h,g,1]]]]]]]]],[0,g,[],[[-1,
A.h.prototype.f.Ei,g,[[11,"tomove"],[7,[19,A.h.prototype.d["int"],[[23,"tomove"]]]]]]]]]],[0,g,[[6,A.b.c.prototype.g.tb,g,h,h,h,f,[[4,4]]]],[[-1,A.h.prototype.f.ea,g,[[11,"die"],[7,[0,1]]]]]],[0,g,[[-1,A.h.prototype.g.Kc,g,h,h,h,h,[[11,"die"],[8,0],[7,[0,1]]]],[1,A.b.i.prototype.g.nc,g,h,h,h,h]],[[1,A.b.i.prototype.f.Mc,g],[6,A.b.c.prototype.f.Me,g,[[0,[21,6,h,g,0]],[0,[21,6,h,g,1]]]],[6,A.b.c.prototype.f.qc,g,[[10,5],[3,0]]],[6,A.b.c.prototype.f.O,g,[[10,2],[7,[0,-1]]]]]],[0,[f,"controls"],[[-1,
A.h.prototype.g.Je,g,h,h,h,h,[[1,[2,"controls"]]]]],[],[[1,"move",0,0],[1,"old_dir",0,0],[0,g,[],[[-1,A.h.prototype.f.ea,g,[[11,"old_dir"],[7,[21,6,h,g,3]]]]]],[0,g,[[7,A.b.Ta.prototype.g.Bd,g,h,h,h,h,[[9,37]]]],[[6,A.b.c.prototype.f.O,g,[[10,3],[7,[0,180]]]],[-1,A.h.prototype.f.ea,g,[[11,"move"],[7,[0,1]]]]]],[0,g,[[7,A.b.Ta.prototype.g.Bd,g,h,h,h,h,[[9,39]]]],[[6,A.b.c.prototype.f.O,g,[[10,3],[7,[0,0]]]],[-1,A.h.prototype.f.ea,g,[[11,"move"],[7,[0,1]]]]]],[0,g,[[7,A.b.Ta.prototype.g.Bd,g,h,h,h,
h,[[9,38]]]],[[6,A.b.c.prototype.f.O,g,[[10,3],[7,[0,270]]]],[-1,A.h.prototype.f.ea,g,[[11,"move"],[7,[0,1]]]]]],[0,g,[[7,A.b.Ta.prototype.g.Bd,g,h,h,h,h,[[9,40]]]],[[6,A.b.c.prototype.f.O,g,[[10,3],[7,[0,90]]]],[-1,A.h.prototype.f.ea,g,[[11,"move"],[7,[0,1]]]]]],[0,g,[[1,A.b.i.prototype.g.Ai,g,h,h,h,h,[[0,[21,6,h,g,2]]]]],[[1,A.b.i.prototype.f.Me,g,[[0,[19,A.h.prototype.d.min,[[21,1,h,g,0],[20,6,A.b.c.prototype.d.K,h,g]]]],[0,[19,A.h.prototype.d.min,[[21,1,h,g,1],[20,6,A.b.c.prototype.d.I,h,g]]]]]],
[1,A.b.i.prototype.f.rc,g,[[0,[4,[19,A.h.prototype.d.Da,[[19,A.h.prototype.d.abs,[[5,[20,6,A.b.c.prototype.d.K,h,g],[21,1,h,g,0]]]],[0,0],[0,1E3]]],[0,16]]],[0,[4,[19,A.h.prototype.d.Da,[[19,A.h.prototype.d.abs,[[5,[20,6,A.b.c.prototype.d.I,h,g],[21,1,h,g,1]]]],[0,0],[0,1E3]]],[0,16]]]]]]],[0,g,[[6,A.b.c.prototype.g.ii,g,h,h,h,h,[[10,3],[8,1],[7,[23,"old_dir"]]]]],[[6,A.b.c.prototype.f.qc,g,[[10,4],[3,1]]]]],[0,g,[[6,A.b.c.prototype.g.tb,g,h,h,f,f,[[4,0]]]],[[6,A.b.c.prototype.f.qc,g,[[10,5],[3,0]]],
[6,A.b.c.prototype.f.O,g,[[10,0],[7,[20,6,A.b.c.prototype.d.K,h,g]]]],[6,A.b.c.prototype.f.O,g,[[10,1],[7,[20,6,A.b.c.prototype.d.I,h,g]]]]],[[0,g,[[-1,A.h.prototype.g.Gi,g,h,h,h,h]],[[6,A.b.c.prototype.f.O,g,[[10,2],[7,[0,-1]]]]],[[0,g,[[-1,A.h.prototype.g.Kc,g,h,h,h,h,[[11,"die"],[8,0],[7,[0,0]]]]],[[-1,A.h.prototype.f.ng,g,[[1,[2,"split"]],[3,1]]]]]]]]],[0,g,[[6,A.b.c.prototype.g.tb,g,h,h,h,f,[[4,0]]]],[],[[0,g,[[6,A.b.c.prototype.g.hg,g,h,h,f,h,[[10,5]]]],[[6,A.b.c.prototype.f.qc,g,[[10,4],[3,
0]]],[6,A.b.c.prototype.f.qc,g,[[10,5],[3,1]]],[-1,A.h.prototype.f.Lc,g,[[4,1],[5,[0,1]],[0,[21,6,h,g,0]],[0,[21,6,h,g,1]]]],[1,A.b.i.prototype.f.O,g,[[10,0],[7,[20,1,A.b.i.prototype.d.K,h,g]]]],[1,A.b.i.prototype.f.O,g,[[10,1],[7,[20,1,A.b.i.prototype.d.I,h,g]]]],[6,A.b.c.prototype.f.O,g,[[10,2],[7,[20,1,A.b.i.prototype.d.qg,h,g]]]],[6,A.b.c.prototype.f.jg,g]]],[0,g,[[6,A.b.c.prototype.g.hg,g,h,h,h,h,[[10,4]]]],[[6,A.b.c.prototype.f.qc,g,[[10,4],[3,0]]],[-1,A.h.prototype.f.Lc,g,[[4,1],[5,[0,1]],
[0,[20,6,A.b.c.prototype.d.K,h,g]],[0,[20,6,A.b.c.prototype.d.I,h,g]]]],[1,A.b.i.prototype.f.O,g,[[10,0],[7,[20,1,A.b.i.prototype.d.K,h,g]]]],[1,A.b.i.prototype.f.O,g,[[10,1],[7,[20,1,A.b.i.prototype.d.I,h,g]]]],[6,A.b.c.prototype.f.O,g,[[10,2],[7,[20,1,A.b.i.prototype.d.qg,h,g]]]],[6,A.b.c.prototype.f.jg,g]]]]],[0,g,[[-1,A.h.prototype.g.Kc,g,h,h,h,h,[[11,"move"],[8,0],[7,[0,1]]]]],[[6,A.b.c.prototype.f.pi,g,[[0,[21,6,h,g,3]],[0,[19,A.h.prototype.d["int"],[[6,[0,100],[19,A.h.prototype.d.xb]]]]]]]]]]],
[0,[h,"split"],[[-1,A.h.prototype.g.Je,g,h,h,h,h,[[1,[2,"split"]]]]],[],[[0,g,[],[[-1,A.h.prototype.f.ng,g,[[1,[2,"split"]],[3,0]]]]],[0,g,[[1,A.b.i.prototype.g.nc,g,h,h,h,h]],[],[[0,g,[],[[1,A.b.i.prototype.f.O,g,[[10,0],[7,[20,1,A.b.i.prototype.d.K,h,g]]]],[1,A.b.i.prototype.f.O,g,[[10,1],[7,[20,1,A.b.i.prototype.d.I,h,g]]]],[1,A.b.i.prototype.f.O,g,[[10,2],[7,[20,1,A.b.i.prototype.d.Ia,h,g]]]],[1,A.b.i.prototype.f.O,g,[[10,3],[7,[20,1,A.b.i.prototype.d.Sa,h,g]]]]]],[0,g,[[-1,A.h.prototype.g.Ad,
g,h,f,h,h,[[4,1]]],[0,A.b.c.prototype.g.tb,g,h,h,h,f,[[4,1]]],[-1,A.h.prototype.g.Ad,g,h,f,h,h,[[4,0]]]],[],[[1,"w",0,0],[1,"w2",0,0],[1,"h",0,0],[1,"h2",0,0],[0,g,[[1,A.b.i.prototype.g.eg,g,h,h,h,h,[[8,2],[0,[20,0,A.b.c.prototype.d.K,h,g]]]]],[[1,A.b.i.prototype.f.Ne,g,[[0,[19,A.h.prototype.d.Da,[[5,[20,1,A.b.i.prototype.d.Ia,h,g],[5,[20,0,A.b.c.prototype.d.K,h,g],[20,1,A.b.i.prototype.d.K,h,g]]],[0,0],[0,1E3]]]]]],[1,A.b.i.prototype.f.Cd,g,[[0,[20,0,A.b.c.prototype.d.K,h,g]]]]]],[0,g,[[1,A.b.i.prototype.g.Ge,
g,h,h,h,h,[[8,2],[0,[20,0,A.b.c.prototype.d.I,h,g]]]]],[[1,A.b.i.prototype.f.og,g,[[0,[19,A.h.prototype.d.Da,[[5,[20,1,A.b.i.prototype.d.Sa,h,g],[5,[20,0,A.b.c.prototype.d.I,h,g],[20,1,A.b.i.prototype.d.I,h,g]]],[0,0],[0,1E3]]]]]],[1,A.b.i.prototype.f.Dd,g,[[0,[20,0,A.b.c.prototype.d.I,h,g]]]]]],[0,g,[],[[1,A.b.i.prototype.f.rc,g,[[0,[5,[19,A.h.prototype.d.Da,[[4,[5,[20,1,A.b.i.prototype.d.K,h,g],[20,0,A.b.c.prototype.d.K,h,g]],[20,1,A.b.i.prototype.d.Ia,h,g]],[0,0],[20,0,A.b.c.prototype.d.Ia,h,g]]],
[5,[20,1,A.b.i.prototype.d.K,h,g],[20,0,A.b.c.prototype.d.K,h,g]]]],[0,[5,[19,A.h.prototype.d.Da,[[4,[5,[20,1,A.b.i.prototype.d.I,h,g],[20,0,A.b.c.prototype.d.I,h,g]],[20,1,A.b.i.prototype.d.Sa,h,g]],[0,0],[20,0,A.b.c.prototype.d.Sa,h,g]]],[5,[20,1,A.b.i.prototype.d.I,h,g],[20,0,A.b.c.prototype.d.I,h,g]]]]]]]],[0,g,[[1,A.b.i.prototype.g.eg,g,h,h,h,h,[[8,5],[0,[20,0,A.b.c.prototype.d.K,h,g]]]],[1,A.b.i.prototype.g.Ge,g,h,h,h,h,[[8,2],[0,[4,[20,0,A.b.c.prototype.d.I,h,g],[20,0,A.b.c.prototype.d.Sa,
h,g]]]]]],[[-1,A.h.prototype.f.ea,g,[[11,"w"],[7,[20,0,A.b.c.prototype.d.Ia,h,g]]]],[-1,A.h.prototype.f.ea,g,[[11,"h"],[7,[20,0,A.b.c.prototype.d.Sa,h,g]]]],[0,A.b.c.prototype.f.Ne,g,[[0,[19,A.h.prototype.d.Da,[[5,[20,1,A.b.i.prototype.d.K,h,g],[20,0,A.b.c.prototype.d.K,h,g]],[0,0],[0,1E3]]]]]],[-1,A.h.prototype.f.ea,g,[[11,"w2"],[7,[20,0,A.b.c.prototype.d.Ia,h,g]]]],[-1,A.h.prototype.f.Lc,g,[[4,0],[5,[0,0]],[0,[4,[20,1,A.b.i.prototype.d.K,h,g],[20,1,A.b.i.prototype.d.Ia,h,g]]],[0,[20,0,A.b.c.prototype.d.I,
h,g]]]],[0,A.b.c.prototype.f.rc,g,[[0,[19,A.h.prototype.d.Da,[[5,[5,[23,"w"],[23,"w2"]],[20,1,A.b.i.prototype.d.Ia,h,g]],[0,0],[0,1E3]]]],[0,[23,"h"]]]],[-1,A.h.prototype.f.Lc,g,[[4,0],[5,[0,0]],[0,[20,1,A.b.i.prototype.d.K,h,g]],[0,[20,0,A.b.c.prototype.d.I,h,g]]]],[0,A.b.c.prototype.f.rc,g,[[0,[20,1,A.b.i.prototype.d.Ia,h,g]],[0,[23,"h"]]]]],[[0,g,[[1,A.b.i.prototype.g.Ge,g,h,h,h,h,[[8,5],[0,[20,0,A.b.c.prototype.d.I,h,g]]]]],[[0,A.b.c.prototype.f.og,g,[[0,[19,A.h.prototype.d.Da,[[5,[20,1,A.b.i.prototype.d.I,
h,g],[20,0,A.b.c.prototype.d.I,h,g]],[0,0],[0,1E3]]]]]],[-1,A.h.prototype.f.ea,g,[[11,"h2"],[7,[20,0,A.b.c.prototype.d.Sa,h,g]]]],[-1,A.h.prototype.f.Lc,g,[[4,0],[5,[0,0]],[0,[20,0,A.b.c.prototype.d.K,h,g]],[0,[4,[20,1,A.b.i.prototype.d.I,h,g],[20,1,A.b.i.prototype.d.Sa,h,g]]]]],[0,A.b.c.prototype.f.rc,g,[[0,[20,1,A.b.i.prototype.d.Ia,h,g]],[0,[19,A.h.prototype.d.Da,[[5,[5,[23,"h"],[23,"h2"]],[20,1,A.b.i.prototype.d.Sa,h,g]],[0,0],[0,1E3]]]]]]]]]],[0,g,[],[[1,A.b.i.prototype.f.Me,g,[[0,[21,1,h,g,
0]],[0,[21,1,h,g,1]]]],[1,A.b.i.prototype.f.rc,g,[[0,[21,1,h,g,2]],[0,[21,1,h,g,3]]]]]]]],[0,g,[],[[1,A.b.i.prototype.f.Di,g,[[3,0]]]]]]]]],[0,g,[[0,A.b.c.prototype.g.ki,g,h,h,h,h,[[8,0],[0,[0,0]]]]],[[0,A.b.c.prototype.f.Mc,g]]],[0,g,[[0,A.b.c.prototype.g.hi,g,h,h,h,h,[[8,0],[0,[0,0]]]]],[[0,A.b.c.prototype.f.Mc,g]]],[1,"area",0,0],[0,g,[],[[0,A.b.c.prototype.f.Le,g,[[0,[0,50]]]],[-1,A.h.prototype.f.ea,g,[[11,"area"],[7,[0,0]]]]]],[0,g,[[-1,A.h.prototype.g.Ad,g,h,f,h,h,[[4,0]]]],[[-1,A.h.prototype.f.cg,
g,[[11,"area"],[7,[6,[20,0,A.b.c.prototype.d.Ia,h,g],[20,0,A.b.c.prototype.d.Sa,h,g]]]]]]],[0,g,[[4,A.b.c.prototype.g.tb,g,h,h,h,f,[[4,0]]]],[[0,A.b.c.prototype.f.Le,g,[[0,[0,100]]]]]],[0,g,[[-1,A.h.prototype.g.mg,g,h,f,h,h,[[0,[0,20]]]],[0,A.b.c.prototype.g.dg,g,h,h,h,h,[[8,0],[0,[0,100]]]]],[],[[0,g,[[0,A.b.c.prototype.g.tb,g,h,h,h,f,[[4,9]]]],[[9,A.b.c.prototype.f.Le,g,[[0,[0,100]]]]]]]],[0,g,[[0,A.b.c.prototype.g.dg,g,h,h,h,h,[[8,0],[0,[0,50]]]]],[[0,A.b.c.prototype.f.Mc,g]]],[0,g,[[-1,A.h.prototype.g.li,
g,h,h,h,h]],[[-1,A.h.prototype.f.ea,g,[[11,"die"],[7,[0,0]]]],[2,A.b.Oc.prototype.f.Ci,g,[[7,[10,[10,[10,[10,[2,"procent odkrycia: "],[5,[0,100],[7,[19,A.h.prototype.d["int"],[[6,[0,1E3],[7,[23,"area"],[0,239616]]]]],[0,10]]]],[2,"%    "]],[19,A.h.prototype.d.Vd]],[2," fps"]]]]]]]]]],"media/",h,640,480,1,f,f,f,"1.0"]};window.cr=A;window.cr.createRuntime=A.Ri;