{
	"version": 1507374030,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/goku-sheet0.png",
		"images/goku-sheet1.png",
		"images/buttonattack-sheet0.png",
		"images/sfhp.png",
		"images/sflv.png",
		"images/sfattackki.png",
		"images/sfdefki.png",
		"images/sprite-sheet0.png",
		"images/button2-sheet0.png",
		"images/button2-sheet1.png",
		"images/sf-sheet0.png",
		"images/sf2-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/attackicon-default-000.jpg",
		"images/attackicon-default-001.jpg",
		"images/attackicon-default-002.jpg",
		"images/attackicon-default-003.jpg",
		"images/attackicon-sheet0.png",
		"images/attackicon-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/buttonatkki-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/gokufist-sheet0.png",
		"images/enemyfist-sheet0.png",
		"images/button3-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/enemy-sheet0.png",
		"images/background-default-000.jpg",
		"images/hitpunchanimation-sheet0.png",
		"images/hpenemy-sheet0.png",
		"images/damenemytext.png",
		"images/sprite7-sheet0.png",
		"images/particles.png",
		"images/dragonballswallpaper-default-000.jpg",
		"images/mu-sheet0.png",
		"images/listeunivers-sheet0.png",
		"images/turnball1-sheet0.png",
		"images/turnball1-sheet1.png",
		"images/turnball2-sheet0.png",
		"images/turnball2-sheet1.png",
		"images/button4-sheet0.png",
		"images/bigbangattack-sheet0.png",
		"images/aura-sheet0.png",
		"images/bigexplosion-sheet0.png",
		"images/kiblastenemy-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite8-sheet1.png",
		"images/sprite9-sheet0.png",
		"images/cooltext-sheet0.png",
		"images/cooltext2-sheet0.png",
		"images/hpenemy2-sheet0.png",
		"images/beam-sheet0.png",
		"images/kameha-sheet0.png",
		"images/aura2-sheet0.png",
		"images/aura2-sheet1.png",
		"images/points.png",
		"images/kame-sheet0.png",
		"images/adwdad-default-000.jpg",
		"images/rb2_ova_new_goku-sheet0.png",
		"images/finalflash-sheet0.png",
		"media/dbz defend hit.m4a",
		"media/dbz defend hit.ogg",
		"media/dbz hit punch.m4a",
		"media/dbz hit punch.ogg",
		"media/dbz attack punch.m4a",
		"media/dbz attack punch.ogg",
		"media/dbz hit punch ground.m4a",
		"media/dbz hit punch ground.ogg",
		"media/db select.m4a",
		"media/db select.ogg",
		"media/db turn.m4a",
		"media/db turn.ogg",
		"media/dbz big blast).m4a",
		"media/dbz big blast).ogg",
		"media/explosion.m4a",
		"media/explosion.ogg",
		"media/dragonball z sound effects (charge big bang).m4a",
		"media/dragonball z sound effects (charge big bang).ogg",
		"media/dragonball z sound effects (click).m4a",
		"media/dragonball z sound effects (click).ogg",
		"media/dragonball z sound effects (kiblast).m4a",
		"media/dragonball z sound effects (kiblast).ogg",
		"media/dragonball z sound effects (fly).m4a",
		"media/dragonball z sound effects (fly).ogg",
		"media/dragonball z sound effects (duel).m4a",
		"media/dragonball z sound effects (duel).ogg",
		"media/dragonball z sound effects (punch2).m4a",
		"media/dragonball z sound effects (punch2).ogg",
		"media/dragonball z sound effects (punch3).m4a",
		"media/dragonball z sound effects (punch3).ogg",
		"media/dragonball z sound effects (kiblast2).m4a",
		"media/dragonball z sound effects (kiblast2).ogg",
		"media/dragonball z sound effects (teleport).m4a",
		"media/dragonball z sound effects (teleport).ogg",
		"media/dragonball z sound effects (480p.kameha).m4a",
		"media/dragonball z sound effects (480p.kameha).ogg",
		"media/dragonball z sound effects (gain).m4a",
		"media/dragonball z sound effects (gain).ogg",
		"media/teleport.m4a",
		"media/teleport.ogg",
		"media/kame hame ha! 1.m4a",
		"media/kame hame ha! 1.ogg",
		"media/super saiyan transformacion.m4a",
		"media/super saiyan transformacion.ogg",
		"media/intros_003.m4a",
		"media/intros_003.ogg",
		"media/revontuelt.m4a",
		"media/revontuelt.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}